// ValueKit — reads option definitions and stored answers in every saved shape:
// normalizeOption, readBoolean, readChoice and readDate. Non-rendering helper
// module in the FormulaKit pattern: one namespace object, so consumers keep a
// single bare identifier in engine scope and reference it only inside function
// bodies (component files load in no guaranteed order).
//
// Generated by scripts/generate-value-kit.mjs from packages/form-model/src/values.ts.
// Do not edit: change values.ts and run `pnpm generate:nhforms`. The shared
// case table (values.cases.ts) holds both implementations to the same results.

const ValueKit = (() => {
  function isRecord(value) {
    return value !== null && typeof value === "object" && !Array.isArray(value) && !(value instanceof Date);
  }
  function scalarText(value) {
    if (typeof value === "string") return value.trim() ? value : void 0;
    if (typeof value === "number") return Number.isFinite(value) ? String(value) : void 0;
    if (typeof value === "boolean") return String(value);
    return void 0;
  }
  function firstText(record, keys) {
    for (const key of keys) {
      const text = scalarText(record[key]);
      if (text !== void 0) return text;
    }
    return void 0;
  }
  function finiteNumber(value) {
    if (typeof value === "number") return Number.isFinite(value) ? value : void 0;
    if (typeof value === "string" && value.trim()) {
      const parsed = Number(value);
      return Number.isFinite(parsed) ? parsed : void 0;
    }
    return void 0;
  }
  var FHIR_SCORE_EXTENSION = /\/(ordinalValue|itemWeight)$/;
  function fhirExtensionScore(extensions) {
    if (!Array.isArray(extensions)) return void 0;
    for (const extension of extensions) {
      if (!isRecord(extension) || typeof extension.url !== "string" || !FHIR_SCORE_EXTENSION.test(extension.url)) continue;
      const score = finiteNumber(extension.valueDecimal ?? extension.valueInteger);
      if (score !== void 0) return score;
    }
    return void 0;
  }
  var FHIR_ANSWER_KEYS = ["valueCoding", "valueString", "valueInteger", "valueDecimal", "valueDate", "valueTime"];
  function fhirAnswerValue(record) {
    for (const key of FHIR_ANSWER_KEYS) {
      if (record[key] !== void 0 && record[key] !== null) return record[key];
    }
    return void 0;
  }
  var OPTION_CODE_KEYS = ["value", "code", "key", "id", "state"];
  var ORDINAL_OPTION_CODE_KEYS = ["code", "key", "id", "state", "value"];
  var OPTION_DISPLAY_KEYS = ["label", "display", "text"];
  function withOptional(option, system, score) {
    if (system !== void 0) option.system = system;
    if (score !== void 0) option.score = score;
    return option;
  }
  function normalizeOption(raw) {
    if (raw === null || raw === void 0) return { code: "", display: "" };
    if (!isRecord(raw)) {
      const text = scalarText(raw) ?? "";
      return { code: text, display: text };
    }
    const fhirValue = fhirAnswerValue(raw);
    if (fhirValue !== void 0 && raw.value === void 0 && raw.code === void 0 && raw.label === void 0) {
      const inner = normalizeOption(fhirValue);
      return withOptional({ code: inner.code, display: inner.display }, inner.system, inner.score ?? fhirExtensionScore(raw.extension));
    }
    const ordinal = typeof raw.value === "number" && Number.isFinite(raw.value) ? raw.value : void 0;
    const code = firstText(raw, ordinal === void 0 ? OPTION_CODE_KEYS : ORDINAL_OPTION_CODE_KEYS);
    const display = firstText(raw, OPTION_DISPLAY_KEYS);
    return withOptional(
      { code: code ?? display ?? "", display: display ?? code ?? "" },
      scalarText(raw.system),
      finiteNumber(raw.score) ?? ordinal
    );
  }
  var BOOLEAN_TRUE_TEXT = ["true", "t", "yes", "y", "on", "1", "checked", "selected", "x"];
  var BOOLEAN_FALSE_TEXT = ["false", "f", "no", "n", "off", "0", "unchecked", "unselected"];
  var BOOLEAN_OBJECT_KEYS = ["code", "selectedKey", "value", "key", "display", "response", "text", "label"];
  function normalizedLabel(value) {
    return typeof value === "string" ? value.trim().toLowerCase() : "";
  }
  function readBoolean(value, labels) {
    if (value === true || value === false) return value;
    if (value === null || value === void 0) return null;
    if (typeof value === "number") return value === 1 ? true : value === 0 ? false : null;
    if (typeof value === "string") {
      const text = value.trim().toLowerCase();
      if (!text) return null;
      const on = normalizedLabel(labels?.on);
      const off = normalizedLabel(labels?.off);
      if (on && text === on) return true;
      if (off && text === off) return false;
      if (BOOLEAN_TRUE_TEXT.includes(text)) return true;
      if (BOOLEAN_FALSE_TEXT.includes(text)) return false;
      return null;
    }
    if (Array.isArray(value)) return value.length === 1 ? readBoolean(value[0], labels) : null;
    if (isRecord(value)) {
      for (const key of BOOLEAN_OBJECT_KEYS) {
        const result = readBoolean(value[key], labels);
        if (result !== null) return result;
      }
    }
    return null;
  }
  var CHOICE_CODE_KEYS = ["code", "value", "key", "id"];
  var CHOICE_DISPLAY_KEYS = ["display", "response", "label", "text"];
  function choiceValue(code, display, system) {
    const entry = { code };
    if (display !== void 0) entry.display = display;
    if (system !== void 0) entry.system = system;
    return entry;
  }
  function readChoiceEntries(value) {
    if (value === null || value === void 0) return [];
    if (Array.isArray(value)) return value.flatMap(readChoiceEntries);
    if (!isRecord(value)) {
      const code2 = scalarText(value);
      return code2 === void 0 ? [] : [{ code: code2 }];
    }
    if (Array.isArray(value.coding)) return readChoiceEntries(value.coding[0]);
    if (isRecord(value.valueCoding)) return readChoiceEntries(value.valueCoding);
    if (Array.isArray(value.selectedItems)) return value.selectedItems.flatMap(readChoiceEntries);
    if ("selectedItem" in value) return readChoiceEntries(value.selectedItem);
    if ("selectedKey" in value) {
      const code2 = scalarText(value.selectedKey);
      if (code2 === void 0) return [];
      return [choiceValue(code2, firstText(value, ["response", "display", "text", "label"]), scalarText(value.system))];
    }
    if (Array.isArray(value.selectedIds) || Array.isArray(value.selectedLabels)) {
      const ids = Array.isArray(value.selectedIds) ? value.selectedIds : [];
      const labels = Array.isArray(value.selectedLabels) ? value.selectedLabels : [];
      const entries = [];
      for (let index = 0; index < Math.max(ids.length, labels.length); index += 1) {
        const label = scalarText(labels[index]);
        const code2 = scalarText(ids[index]) ?? label;
        if (code2 !== void 0) entries.push(choiceValue(code2, label, void 0));
      }
      return entries;
    }
    if (value.value !== null && typeof value.value === "object") return readChoiceEntries(value.value);
    const display = firstText(value, CHOICE_DISPLAY_KEYS);
    const code = firstText(value, CHOICE_CODE_KEYS) ?? display;
    return code === void 0 ? [] : [choiceValue(code, display, scalarText(value.system))];
  }
  function sameText(left, right) {
    return left !== void 0 && right !== void 0 && left.trim().toLowerCase() === right.trim().toLowerCase();
  }
  function resolveAgainstOptions(entry, options) {
    const match = options.find((option) => option.code === entry.code) ?? options.find((option) => sameText(option.code, entry.code)) ?? options.find((option) => sameText(option.display, entry.code) || sameText(option.display, entry.display));
    if (!match) return entry;
    return choiceValue(match.code, match.display, entry.system ?? match.system);
  }
  function readChoice(value, options) {
    const entries = readChoiceEntries(value);
    if (!Array.isArray(options) || options.length === 0 || entries.length === 0) return entries;
    const normalized = options.map(normalizeOption).filter((option) => option.code !== "" || option.display !== "");
    return entries.map((entry) => resolveAgainstOptions(entry, normalized));
  }
  var DATE_FORMATS = [
    { pattern: /^(\d{4})-(\d{1,2})-(\d{1,2})/, order: [1, 2, 3] },
    // yyyy-MM-dd
    { pattern: /^(\d{4})\.(\d{1,2})\.(\d{1,2})/, order: [1, 2, 3] },
    // yyyy.MM.dd (DateSelect default)
    { pattern: /^(\d{4})\/(\d{1,2})\/(\d{1,2})/, order: [1, 2, 3] },
    // yyyy/MM/dd
    { pattern: /^(\d{1,2})\/(\d{1,2})\/(\d{4})/, order: [3, 2, 1] },
    // dd/MM/yyyy
    { pattern: /^(\d{1,2})-(\d{1,2})-(\d{4})/, order: [3, 1, 2] }
    // MM-dd-yyyy
  ];
  var TIME_SUFFIX = /^(?:[T ]|\s+)(\d{1,2}):(\d{2})(?::(\d{2})(?:\.(\d{1,9}))?)?\s*(Z|[+-]\d{2}:?\d{2})?$/i;
  function parseDateText(text) {
    const trimmed = text.trim();
    for (const format of DATE_FORMATS) {
      const match = format.pattern.exec(trimmed);
      if (!match) continue;
      const [year, month, day] = format.order.map((index) => Number(match[index]));
      const midnight = new Date(year, month - 1, day);
      if (midnight.getFullYear() !== year || midnight.getMonth() !== month - 1 || midnight.getDate() !== day) return null;
      const rest = trimmed.slice(match[0].length);
      if (rest === "") return { date: midnight, dateOnly: true };
      const time = TIME_SUFFIX.exec(rest);
      if (!time) return null;
      const hours = Number(time[1]);
      const minutes = Number(time[2]);
      const seconds = time[3] ? Number(time[3]) : 0;
      const millis = time[4] ? Number(time[4].slice(0, 3).padEnd(3, "0")) : 0;
      if (hours > 23 || minutes > 59 || seconds > 59) return null;
      if (!time[5]) return { date: new Date(year, month - 1, day, hours, minutes, seconds, millis), dateOnly: false };
      const zone = time[5].toUpperCase();
      let offsetMinutes = 0;
      if (zone !== "Z") {
        const digits = zone.replace(":", "");
        offsetMinutes = (Number(digits.slice(1, 3)) * 60 + Number(digits.slice(3, 5))) * (digits[0] === "-" ? -1 : 1);
      }
      return { date: new Date(Date.UTC(year, month - 1, day, hours, minutes, seconds, millis) - offsetMinutes * 6e4), dateOnly: false };
    }
    return null;
  }
  var DATE_OBJECT_KEYS = ["value", "date", "text", "display"];
  function readDateTime(value) {
    if (value === null || value === void 0 || value === "") return null;
    if (value instanceof Date) return Number.isFinite(value.getTime()) ? { date: new Date(value.getTime()), dateOnly: false } : null;
    if (typeof value === "number") {
      if (!Number.isFinite(value)) return null;
      const date = new Date(value);
      return Number.isFinite(date.getTime()) ? { date, dateOnly: false } : null;
    }
    if (typeof value === "string") return value.trim() ? parseDateText(value) : null;
    if (isRecord(value)) {
      for (const key of DATE_OBJECT_KEYS) {
        const date = readDateTime(value[key]);
        if (date) return date;
      }
    }
    return null;
  }
  function readDate(value) {
    return readDateTime(value)?.date ?? null;
  }

  return {
    normalizeOption,
    readBoolean,
    readChoice,
    readDate,
    readDateTime,
  }
})()
