// Generated by scripts/generate-pdf-signing.mjs from scripts/templates/pdf-text-flow-field.jsx and lib/pdf-text-flow.ts.
"use strict";
var PdfTextFlowFieldLayout = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // lib/pdf-text-flow.ts
  var pdf_text_flow_exports = {};
  __export(pdf_text_flow_exports, {
    PDF_TEXT_FLOW_TRUNCATION_MARK: () => PDF_TEXT_FLOW_TRUNCATION_MARK,
    estimatePdfTextFlowCapacity: () => estimatePdfTextFlowCapacity,
    layoutPdfTextFlow: () => layoutPdfTextFlow,
    measureHelvetica: () => measureHelvetica,
    resolveCompositeTextFlowSlots: () => resolveCompositeTextFlowSlots,
    resolvePdfTextFlowSlot: () => resolvePdfTextFlowSlot,
    truncatePdfTextFlow: () => truncatePdfTextFlow
  });
  var HELVETICA_ASCII = [278, 278, 355, 556, 556, 889, 667, 191, 333, 333, 389, 584, 278, 333, 278, 278, 556, 556, 556, 556, 556, 556, 556, 556, 556, 556, 278, 278, 584, 584, 584, 556, 1015, 667, 667, 722, 722, 667, 611, 778, 722, 278, 500, 667, 556, 833, 722, 778, 667, 778, 722, 667, 611, 722, 667, 944, 667, 667, 611, 278, 278, 278, 469, 556, 333, 556, 556, 500, 556, 556, 278, 556, 556, 222, 222, 500, 222, 833, 556, 556, 556, 556, 333, 500, 278, 556, 500, 722, 500, 500, 500, 334, 260, 334, 584];
  var HELVETICA_EXTRA = { 160: 278, 173: 333, 176: 400, 181: 556, 183: 278, 8211: 556, 8212: 1e3, 8216: 222, 8217: 222, 8220: 333, 8221: 333, 8226: 350, 8230: 1e3 };
  var HELVETICA_FALLBACK = 556;
  var PDF_TEXT_FLOW_TRUNCATION_MARK = " \u2026";
  function measureHelvetica(text, fontSize) {
    let units = 0;
    for (const char of text) {
      const code = char.codePointAt(0) ?? 0;
      units += code >= 32 && code <= 126 ? HELVETICA_ASCII[code - 32] : HELVETICA_EXTRA[code] ?? HELVETICA_FALLBACK;
    }
    return units * fontSize / 1e3;
  }
  function resolvePdfTextFlowSlot(fieldId, bbox, declaredFontSize) {
    const fontSize = declaredFontSize && declaredFontSize > 0 ? declaredFontSize : Math.min(10, Math.max(6, bbox.height - 3));
    return { fieldId, width: Math.max(0, bbox.width - 8), fontSize };
  }
  function resolveCompositeTextFlowSlots(composite, lookup) {
    const snapshotBox = new Map((composite.componentSnapshots ?? []).map((snapshot) => [snapshot.id, snapshot.bbox ?? null]));
    const slots = [];
    for (const { fieldId } of composite.components) {
      const box = snapshotBox.get(fieldId) ?? lookup?.(fieldId) ?? null;
      if (!box || !(box.width > 0) || !(box.height > 0)) return null;
      slots.push(resolvePdfTextFlowSlot(fieldId, box));
    }
    return slots.length >= 2 ? slots : null;
  }
  var TYPICAL_TEXT = "Give 2 tabs PO at bedtime if no bowel movement in 48 hours; reassess daily.";
  var WRAP_LOSS_CHARS = 3;
  function typicalCharWidth(fontSize) {
    return measureHelvetica(TYPICAL_TEXT, fontSize) / TYPICAL_TEXT.length;
  }
  function estimatePdfTextFlowCapacity(slots) {
    return layoutPdfTextFlow("", slots).remainingChars;
  }
  var isLetter = (char) => Boolean(char) && /[A-Za-z\u00C0-\u024F]/.test(char);
  var NUMBER_START = /^[<>~+\u2264\u2265-]?\d/;
  var UNIT_WORD = /^(?:mg|mcg|\u00b5g|g|kg|ml|l|units?|iu|tabs?|tablets?|caps?|capsules?|sachets?|packets?|drops?|puffs?|sprays?|mmol|meq|%|h|hrs?|hours?|d|days?|min|mins|minutes?|weeks?|times?|x|doses?|suppositor(?:y|ies)|enemas?)[.,;:)]*$/i;
  var SOFT_HYPHEN = "\xAD";
  var stripSoftHyphens = (value) => value.split(SOFT_HYPHEN).join("");
  function layoutPdfTextFlow(text, slots, measure = measureHelvetica) {
    const lines = slots.map(() => "");
    const source = String(text ?? "").replace(/\r\n?/g, "\n");
    let index = 0;
    let overflowAt = -1;
    const fitsOn = (value) => measure(value, slots[index].fontSize) <= slots[index].width;
    const breakInside = (word, prefix) => {
      let best = null;
      for (let i = 1; i < word.length; i += 1) {
        const before = word[i - 1];
        let head = null;
        if (before === SOFT_HYPHEN) head = `${stripSoftHyphens(word.slice(0, i - 1))}-`;
        else if ((before === "-" || before === "/") && isLetter(word[i - 2]) && isLetter(word[i])) head = stripSoftHyphens(word.slice(0, i));
        if (head === null) continue;
        if (!fitsOn(prefix + head)) break;
        best = { head, consumed: i };
      }
      return best;
    };
    const forceSplit = (word) => {
      const chars = Array.from(stripSoftHyphens(word));
      let best = null;
      for (let count = 1; count < chars.length; count += 1) {
        const head = chars.slice(0, count).join("");
        if (!fitsOn(head)) break;
        best = { head, consumed: head.length };
      }
      if (!best) return null;
      let seen = 0;
      let consumed = 0;
      while (consumed < word.length && seen < best.consumed) {
        if (word[consumed] !== SOFT_HYPHEN) seen += 1;
        consumed += 1;
      }
      return { head: best.head, consumed };
    };
    const placeWord = (token) => {
      let word = token.text;
      let wordStart = token.start;
      while (word) {
        if (index >= slots.length) {
          overflowAt = wordStart;
          return false;
        }
        const prefix = lines[index] ? `${lines[index]} ` : "";
        const whole = stripSoftHyphens(word);
        if (fitsOn(prefix + whole)) {
          lines[index] = prefix + whole;
          return true;
        }
        const cut = breakInside(word, prefix) ?? (prefix ? null : forceSplit(word));
        if (cut) {
          lines[index] = prefix + cut.head;
          word = word.slice(cut.consumed);
          wordStart += cut.consumed;
        } else if (!prefix) {
          throw new Error("A PDF text line is too narrow for its font.");
        }
        index += 1;
      }
      return true;
    };
    let offset = 0;
    const paragraphs = source.split("\n");
    outer: for (let p = 0; p < paragraphs.length; p += 1) {
      const paragraph = paragraphs[p];
      const tokens = [];
      const pattern = /\S+/g;
      let match;
      while (match = pattern.exec(paragraph)) tokens.push({ text: match[0], start: offset + match.index });
      offset += paragraph.length + 1;
      const runs = [];
      tokens.forEach((token, tokenIndex) => {
        const previous = tokens[tokenIndex - 1];
        const glued = previous && (NUMBER_START.test(token.text) || NUMBER_START.test(previous.text) && UNIT_WORD.test(token.text));
        if (glued) runs[runs.length - 1].push(token);
        else runs.push([token]);
      });
      if (p > 0 && runs.length && index < slots.length && lines[index]) index += 1;
      for (const run of runs) {
        if (run.length > 1) {
          if (index >= slots.length) {
            overflowAt = run[0].start;
            break outer;
          }
          const joined = run.map((token) => stripSoftHyphens(token.text)).join(" ");
          if (lines[index] && !fitsOn(`${lines[index]} ${joined}`)) index += 1;
          if (index >= slots.length) {
            overflowAt = run[0].start;
            break outer;
          }
          if (fitsOn(lines[index] ? `${lines[index]} ${joined}` : joined)) {
            lines[index] = lines[index] ? `${lines[index]} ${joined}` : joined;
            continue;
          }
        }
        for (const token of run) {
          if (!placeWord(token)) break outer;
        }
      }
    }
    const fits = overflowAt < 0;
    const usedLines = lines.filter(Boolean).length;
    let remainingChars = 0;
    if (fits) {
      const current = Math.min(usedLines === 0 ? 0 : lines.reduce((last, line, lineIndex) => line ? lineIndex : last, 0), slots.length - 1);
      let width = 0;
      let lineBreaks = 0;
      slots.forEach((slot, slotIndex) => {
        if (slotIndex < current) return;
        const used = slotIndex === current && lines[slotIndex] ? measure(`${lines[slotIndex]} `, slot.fontSize) : 0;
        width += Math.max(0, slot.width - used) / typicalCharWidth(slot.fontSize);
        if (slotIndex > current) lineBreaks += 1;
      });
      remainingChars = Math.max(0, Math.floor(width) - WRAP_LOSS_CHARS * lineBreaks);
    }
    return { lines, fits, overflowText: fits ? "" : source.slice(overflowAt).trim(), usedLines, remainingChars };
  }
  function truncatePdfTextFlow(layout, slots, measure = measureHelvetica) {
    if (layout.fits) return { lines: layout.lines, notPrinted: "" };
    const lines = [...layout.lines];
    const last = lines.length - 1;
    const full = lines[last];
    let text = full;
    while (text && measure(text + PDF_TEXT_FLOW_TRUNCATION_MARK, slots[last].fontSize) > slots[last].width) {
      const space = text.lastIndexOf(" ");
      text = space > 0 ? text.slice(0, space) : "";
    }
    lines[last] = `${text}${PDF_TEXT_FLOW_TRUNCATION_MARK}`.trimStart();
    const dropped = full.slice(text.length).trim();
    return { lines, notPrinted: dropped ? `${dropped} ${layout.overflowText}` : layout.overflowText };
  }
  return __toCommonJS(pdf_text_flow_exports);
})();

// A TextArea for a Flow text answer, with a live meter for the PDF lines it
// fills. PdfTextFlowFieldLayout is lib/pdf-text-flow.ts bundled in by
// scripts/generate-pdf-signing.mjs, the same layout PdfRegenerator uses to write
// the PDF, so the meter breaks lines exactly where the saved PDF will.
const PdfTextFlowField = (props) => {
  const { textFlowSlots, textFlowOverflow = "block", ...textAreaProps } = props
  const [fd] = useActiveData(useSection().activeSelector)
  const [showLines, setShowLines] = React.useState(false)
  const raw = fd ? fd[props.fieldId] : undefined
  const text = typeof raw === "string" ? raw : raw == null ? "" : String(raw)
  const layout = React.useMemo(() => {
    if (!Array.isArray(textFlowSlots) || textFlowSlots.length < 2) return null
    try {
      return PdfTextFlowFieldLayout.layoutPdfTextFlow(text, textFlowSlots)
    } catch (error) {
      return null
    }
  }, [text, textFlowSlots])
  const hideOnPrint = Fluent.mergeStyles({ "@media print": { display: "none !important" } })

  if (!layout) return <TextArea {...textAreaProps} />

  const slots = textFlowSlots
  const truncate = textFlowOverflow === "truncate"
  const cut = !layout.fits && truncate ? PdfTextFlowFieldLayout.truncatePdfTextFlow(layout, slots) : null
  const printed = cut ? cut.lines : layout.lines
  const notPrinted = cut ? cut.notPrinted : layout.overflowText
  const over = notPrinted.length
  const hasText = text.trim().length > 0
  const color = layout.fits ? "#605e5c" : truncate ? "#8a5a00" : "#a4262c"
  const message = layout.fits
    ? hasText
      ? `Fits the PDF: ${layout.usedLines} of ${slots.length} lines used, about ${layout.remainingChars} characters left.`
      : `Prints on ${slots.length} PDF lines, about ${layout.remainingChars} characters.`
    : truncate
      ? `About ${over} characters won't print. The PDF's last line ends with "…"; the full answer stays in the form.`
      : `About ${over} characters too long for the PDF's ${slots.length} lines. Shorten the answer before saving the PDF.`

  return (
    <div>
      <TextArea {...textAreaProps} />
      <div className={hideOnPrint} style={{ marginTop: 4 }}>
        <div style={{ display: "flex", gap: 3 }} aria-hidden="true">
          {slots.map((slot, index) => {
            const used = Math.min(1, PdfTextFlowFieldLayout.measureHelvetica(printed[index] || "", slot.fontSize) / slot.width)
            const full = !layout.fits && index === slots.length - 1
            return (
              <div key={slot.fieldId || index} title={printed[index] || ""} style={{ flex: slot.width, height: 4, borderRadius: 2, overflow: "hidden", background: "#edebe9" }}>
                <div style={{ width: `${Math.round(used * 100)}%`, height: "100%", background: full ? color : "#0078d4" }} />
              </div>
            )
          })}
        </div>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", gap: 8, marginTop: 2, fontSize: 12, color }}>
          <span role="status">{message}</span>
          {hasText ? (
            <button
              type="button"
              onClick={() => setShowLines(!showLines)}
              aria-expanded={showLines}
              style={{ border: "none", background: "none", padding: 0, color: "#0078d4", cursor: "pointer", fontSize: 12, whiteSpace: "nowrap" }}
            >
              {showLines ? "Hide PDF lines" : "Show PDF lines"}
            </button>
          ) : null}
        </div>
        {showLines ? (
          <div style={{ marginTop: 4, fontSize: 12, fontFamily: "Helvetica, Arial, sans-serif" }}>
            {printed.map((line, index) => (
              <div key={index} style={{ display: "flex", gap: 6, borderBottom: "1px solid #c8c6c4", padding: "1px 0" }}>
                <span style={{ color: "#605e5c", minWidth: 44 }}>{`Line ${index + 1}`}</span>
                <span style={{ whiteSpace: "pre-wrap" }}>{line || " "}</span>
              </div>
            ))}
            {!layout.fits ? (
              <div style={{ marginTop: 2, color }}>{`Won't print: ${notPrinted}`}</div>
            ) : null}
          </div>
        ) : null}
      </div>
    </div>
  )
}
