/**
 * The formula semantics as a case table: formula text, answers, expected
 * result. Run by formula/semantics.test.ts against the reference evaluator,
 * and meant to be run unchanged against the generated NHForms FormulaKit so
 * the two cannot drift. The clock is FORMULA_CASE_NOW (local time).
 *
 * Rows marked `probe` are the disagreements between lib/expressions and
 * FormulaKit listed in the neutral-form-model proposal.
 */

import type { FormulaChartRecord } from "./chart-results";
import type { FormulaIncompleteMode } from "./evaluate";
import type { FormulaDialect } from "./parse";

export interface FormulaSemanticCase {
  formula: string;
  values?: Record<string, unknown>;
  expected: unknown;
  /** Field types by id: dates read as dates, yes/no as booleans; text types make `+` a text join. */
  fieldKinds?: Record<string, string>;
  scoreMaps?: Record<string, Record<string, number>>;
  params?: Record<string, unknown>;
  dialect?: FormulaDialect;
  /** The evaluator's `incomplete` option (default `blank`). */
  incomplete?: FormulaIncompleteMode;
  /** The patient's chart for `latest()`: plain records, read by `chartRecordReader` (FormulaKit takes them as they are). */
  observations?: FormulaChartRecord[];
  /** Compare numbers to 10 decimal places. */
  approx?: true;
  probe?: true;
  note?: string;
}

/** Saturday 26 September 2026, 10:30 local time. */
export const formulaCaseNow = (): Date => new Date(2026, 8, 26, 10, 30, 0);

const chartName = "{patient.name.first} + ifPresent({patient.nickName.text}, \" (\" + {patient.nickName.text} + \")\")";
const suicideRisk =
  'iif([q1] == "No", "LOW", iif([q1] == "Yes" && [q2] == "No", "LOW", iif([q2] == "Yes", iif([q3] == "Yes" || [q4] == "Yes" || [q5] == "Yes", "HIGH", iif([q6] == "Yes", "HIGH", "MODERATE")), "")))';
const idealBodyWeight =
  '[sex] == "F" || [sex] == "Female" ? 45.5 + 2.3 * ([height] / 2.54 - 60) : [sex] == "M" || [sex] == "Male" ? 50 + 2.3 * ([height] / 2.54 - 60) : null';
const correctedWeeks = '[x] == "N/A" || [x] == "-" || [x] == 0 ? "N/A" : floor([x] / 7)';
const pediatricWeight =
  "([a] >= 1 && [a] <= 12) ? (0.5 * [a] + 4) : (([a] >= 13 && [a] <= 60) ? (2 * ([a] / 12) + 8) : (([a] >= 61 && [a] <= 144) ? (3 * ([a] / 12) + 7) : null))";
const countTrueBuckets =
  "iif(countTrue([c1], [c2], [c3], [c4], [c5]) == 0, 0, iif(countTrue([c1], [c2], [c3], [c4], [c5]) == 1, 1, iif(countTrue([c1], [c2], [c3], [c4], [c5]) <= 3, 2, 3)))";

/**
 * A chart for `latest()`: MOIS observations (observationCode, loincCode,
 * collectedDateTime) and FHIR-style records (codes, label, date, status)
 * side by side, as the two hosts hand them over. Times are local, relative
 * to formulaCaseNow (2026-09-26 10:30).
 */
const CHART: FormulaChartRecord[] = [
  { observationCode: "22732", loincCode: "29463-7", value: "70", units: "kg", collectedDateTime: "2026-08-01T08:00:00" },
  { observationCode: "22732", loincCode: "29463-7", value: "72.5", units: "kg", collectedDateTime: "2026-09-25T08:00:00" },
  { observationCode: "22732", loincCode: "29463-7", value: "99", units: "kg", collectedDateTime: "2026-09-26T09:00:00", status: "entered-in-error" },
  { kind: "Observation", label: "Heart Rate", codes: [{ system: "http://loinc.org", code: "8867-4" }], value: 88, unit: "/min", date: "2026-09-26T10:00:00", status: "final" },
  { kind: "Observation", label: "Heart Rate", codes: [{ system: "http://loinc.org", code: "8867-4" }], value: 90, unit: "/min", date: "2026-09-26T10:15:00", status: "preliminary" },
  { kind: "Observation", label: "RASS Score", codes: [{ system: "urn:webforms:cerner:T1978A:dta", code: "4000123" }], value: "-2", date: "2026-09-26T06:00:00", status: "final" },
  { observationCode: "SMOKE", value: "Never smoker", collectedDateTime: "2026-01-01" },
  { loincCode: "1111-1", value: 5, collectedDateTime: "2026-09-26T11:00:00" },
];

export const FORMULA_SEMANTIC_CASES: FormulaSemanticCase[] = [
  // ── The proposal's probe table ──────────────────────────────────────────
  { formula: "a + b", values: { a: "5", b: "3" }, expected: 8, probe: true, note: "numeric text adds; lib/expressions gave \"53\"" },
  { formula: 'contains("xxabcxx", "abc")', expected: true, probe: true, note: "substring for text; FormulaKit gave false" },
  { formula: 'hasValue("  ")', expected: false, probe: true, note: "whitespace-only text is blank; FormulaKit gave true" },
  { formula: "score(true, 5)", expected: 5, probe: true, note: "a number as the map is a checkbox's points; FormulaKit gave 1" },
  { formula: 'score({ value: "Y" }, { Y: 2 })', expected: 2, probe: true, note: "coded answers look up by code, value, label; lib/expressions gave 0" },
  { formula: 'durationBetween("2026-01-01", "2026-01-02T12:00", "days")', expected: 1.5, probe: true, note: "a time on either side counts exact time; lib/expressions gave 1" },
  { formula: "[a] % 2", values: { a: 3 }, expected: 1, probe: true, note: "FormulaKit rejected %" },
  { formula: "min(1, 2)", expected: 1, probe: true, note: "lib/expressions had no min" },

  // ── Arithmetic and number coercion ──────────────────────────────────────
  { formula: "[a] + [b]", values: { a: "5", b: "3" }, expected: 8 },
  { formula: "[a] - [b]", values: { a: 10, b: 4 }, expected: 6 },
  { formula: "[a] * [b]", values: { a: "2.5", b: 4 }, expected: 10 },
  { formula: "[a] / [b]", values: { a: 1, b: 4 }, expected: 0.25 },
  { formula: "[a] / 0", values: { a: 5 }, expected: null, note: "division by zero is blank" },
  { formula: "[a] % 0", values: { a: 5 }, expected: null },
  { formula: "-7 % 3", expected: -1, note: "remainder takes the sign of the dividend" },
  { formula: "2 ^ 3", expected: 8 },
  { formula: "2 ^ 3 ^ 2", expected: 512, note: "^ is right-associative" },
  { formula: "-2 ^ 2", expected: -4, note: "^ binds tighter than unary minus" },
  { formula: "(-2) ^ 2", expected: 4 },
  { formula: "2 ** 3", expected: 8 },
  { formula: "(-8) ^ (1 / 3)", expected: null, note: "not a real number" },
  { formula: "1 + 2 * 3", expected: 7 },
  { formula: "(1 + 2) * 3", expected: 9 },
  { formula: "10 - 4 - 3", expected: 3 },
  { formula: "0.1 + 0.2", expected: 0.30000000000000004, note: "no rounding inside a formula; the field's precision rounds" },
  { formula: "[a] + 1", values: {}, expected: null, note: "missing propagates" },
  { formula: "[a] + 1", values: { a: "   " }, expected: null },
  { formula: "[a] + 1", values: { a: "abc" }, expected: null, note: "non-numeric text is blank, never concatenated" },
  { formula: "[a] + 1", values: { a: "5 kg" }, expected: null },
  { formula: "[a] + 1", values: { a: "0x10" }, expected: null, note: "decimal notation only" },
  { formula: "[a] + 1", values: { a: "1e3" }, expected: 1001 },
  { formula: "[a] + 1", values: { a: Number.NaN }, expected: null },
  { formula: "[a] + [b]", values: { a: true, b: true }, expected: 2, note: "yes/no counts as 1/0" },
  { formula: "[a] + [b]", values: { a: { code: "3", display: "Three" }, b: 1 }, expected: 4, note: "a choice reads by its numeric code" },
  { formula: "[a] * 2", values: { a: { value: 72, unit: "kg" } }, expected: 144 },
  { formula: "[a] + 1", values: { a: ["4"] }, expected: 5, note: "a one-item list reads as its item" },
  { formula: "[a] + 1", values: { a: ["1", "2"] }, expected: null },
  { formula: "-[a]", values: { a: "4" }, expected: -4 },
  { formula: "+[a]", values: { a: "4" }, expected: 4 },
  { formula: "-[a]", values: { a: 0 }, expected: 0 },
  { formula: "[d] + 1", values: { d: "2026-01-01" }, fieldKinds: { d: "date" }, expected: null, note: "dates are not numbers" },

  // ── Text ────────────────────────────────────────────────────────────────
  { formula: "text([a])", values: { a: 5 }, expected: "5" },
  { formula: "text([a])", values: {}, expected: "" },
  { formula: "text([a])", values: { a: { code: "Y", display: "Yes" } }, expected: "Yes", note: "text shows a choice's label" },
  { formula: "text([a])", values: { a: ["a", "b"] }, expected: "a, b" },
  { formula: "text([d])", values: { d: "2026.03.15" }, fieldKinds: { d: "date" }, expected: "2026-03-15" },
  { formula: "text(true)", expected: "true" },
  { formula: 'concat("a", [x], "b")', values: {}, expected: "ab", note: "blank parts add nothing" },
  { formula: "concat([x], [y])", values: {}, expected: null },
  { formula: 'concat("Total: ", 3 + 4)', expected: "Total: 7" },
  { formula: '"Score: " + [s]', values: { s: 5 }, expected: "Score: 5", note: "legacy text join parses to concat()" },
  { formula: '[first] + " " + [last]', values: { first: "Ann", last: "Lee" }, expected: "Ann Lee" },
  { formula: "[first] + [last]", values: { first: "Ann", last: "Lee" }, fieldKinds: { first: "text", last: "text" }, expected: "AnnLee" },
  { formula: "[t] + 30", values: { t: "14:30" }, fieldKinds: { t: "time" }, expected: null, note: "a time is not text to +: arithmetic, blank (checkFormula date-arithmetic); was \"14:3030\"" },
  { formula: "[t] + [u]", values: { t: "14:30", u: "01:00" }, fieldKinds: { t: "time", u: "time" }, expected: null },
  { formula: '"At " + [t]', values: { t: "14:30" }, fieldKinds: { t: "time" }, expected: "At 14:30", note: "a text operand still joins" },
  { formula: '"5" + "3"', expected: "53", note: "text literals are text; field values are not" },
  { formula: '1 + 2 + "a"', expected: "3a" },
  {
    formula: 'iif(hasValue([location]), "Values collected from clinic location " + [location] + ".", "")',
    values: { location: "PG" },
    expected: "Values collected from clinic location PG.",
  },
  { formula: 'iif(hasValue([location]), "At " + [location], "")', values: {}, expected: "" },
  {
    formula: "text(round(coalesce(null, 1 - power(0.9402, exp(ln([age]) - ln([age])))) * 100, 2)) + '%'",
    values: { age: 55 },
    expected: "5.98%",
  },

  // ── Missing values ──────────────────────────────────────────────────────
  { formula: "hasValue([a])", values: {}, expected: false },
  { formula: "hasValue([a])", values: { a: "" }, expected: false },
  { formula: "hasValue([a])", values: { a: 0 }, expected: true },
  { formula: "hasValue([a])", values: { a: false }, expected: true },
  { formula: "hasValue([a])", values: { a: [] }, expected: false },
  { formula: "hasValue([a])", values: { a: ["", " "] }, expected: false },
  { formula: "hasValue([a])", values: { a: { selectedKey: null, value: null, response: null } }, expected: false, note: "ScaleField's unanswered shape" },
  { formula: "hasValue([a])", values: { a: { code: "", display: "" } }, expected: false },
  { formula: "hasValue([a])", values: { a: "x" }, expected: true },
  { formula: "hasValue([a])", values: { a: ["a"] }, expected: true },
  { formula: "coalesce([a], [b], 7)", values: { b: "" }, expected: 7 },
  { formula: "coalesce([a], 7)", values: { a: 0 }, expected: 0 },
  { formula: "coalesce([a], 7)", values: { a: "  " }, expected: 7 },
  { formula: "coalesce([a], [b])", values: {}, expected: null },
  { formula: "iif(true, 1, [missing] + 1)", values: {}, expected: 1, note: "the branch not taken may be blank" },
  { formula: "iif(false, 1)", expected: null },
  { formula: 'iif([a] > 5, "High", "Normal")', values: {}, expected: null, note: "an unknown test gives a blank result" },
  { formula: '[a] > 5 ? "High" : "Normal"', values: { a: 7 }, expected: "High" },
  { formula: '[a] > 5 ? "High" : "Normal"', values: { a: "3" }, expected: "Normal" },
  { formula: "[a] == null", values: {}, expected: true },
  { formula: "[a] == null", values: { a: "" }, expected: true },
  { formula: "[a] == null", values: { a: 0 }, expected: false },
  { formula: '[a] == ""', values: { a: "  " }, expected: true },
  { formula: '[a] != "Yes"', values: {}, expected: true },
  { formula: 'ifPresent([a], "has", "none")', values: { a: 1 }, expected: "has" },
  { formula: 'ifPresent([a], "has", "none")', values: {}, expected: "none" },
  { formula: 'ifPresent([a], "has")', values: {}, expected: null },
  { formula: "[a]", values: { a: undefined }, expected: null },
  { formula: "undefined", expected: null },

  // ── Logic ───────────────────────────────────────────────────────────────
  { formula: "true && false", expected: false },
  { formula: "[a] > 1 && [b] > 1", values: { b: 0 }, expected: false, note: "false wins over unknown" },
  { formula: "[a] > 1 && true", values: {}, expected: null },
  { formula: "[a] > 1 || true", values: {}, expected: true, note: "true wins over unknown" },
  { formula: "[a] > 1 || false", values: {}, expected: null },
  { formula: "![a]", values: { a: false }, expected: true },
  { formula: "![a]", values: {}, expected: null },
  { formula: "not [a]", values: { a: true }, expected: false },
  { formula: "[a] and [b]", values: { a: true, b: "Yes" }, expected: true },
  { formula: "[a] or [b]", values: { a: "No", b: 0 }, expected: false },
  { formula: "[a] >= 1 AND [a] <= 12", values: { a: 5 }, expected: true },
  { formula: "[a] OR [b]", values: { b: 4 }, expected: 4, note: "Cerner OR between values is coalesce" },
  { formula: "([a] > 1) OR ([b] > 1)", values: { a: 2 }, expected: true },
  { formula: 'iif([n], "yes", "no")', values: { n: 0 }, expected: "no" },
  { formula: 'iif([n], "yes", "no")', values: { n: 2 }, expected: "yes" },
  { formula: 'iif([t], "yes", "no")', values: { t: "No" }, expected: "no" },
  { formula: 'iif([t], "yes", "no")', values: { t: "maybe" }, expected: "yes" },
  { formula: 'iif(patient_is_female, 1, 3)', values: { patient_is_female: 1 }, expected: 1 },

  // ── Equality and ordering ───────────────────────────────────────────────
  { formula: '[x] == "Yes"', values: { x: { code: "Y", display: "Yes" } }, expected: true, note: "a choice matches its code, value or label" },
  { formula: '[x] == "Y"', values: { x: { code: "Y", display: "Yes" } }, expected: true },
  { formula: '[x] == "N"', values: { x: { code: "Y", display: "Yes" } }, expected: false },
  { formula: "[x] == true", values: { x: "Yes" }, expected: true },
  { formula: "[x] == true", values: { x: "Y" }, expected: true },
  { formula: "[x] == false", values: { x: { code: "N", display: "No" } }, expected: true },
  { formula: "[x] == 1", values: { x: true }, expected: true },
  { formula: "[x] == 5", values: { x: "5" }, expected: true },
  { formula: '[x] == "5.0"', values: { x: 5 }, expected: true },
  { formula: '[x] == "yes"', values: { x: "Yes" }, expected: false, note: "text equality is case-sensitive" },
  { formula: "[x] == [y]", values: { x: { code: "A", display: "Alpha" }, y: { code: "A", display: "Other" } }, expected: true },
  { formula: '[x] == "A"', values: { x: ["A"] }, expected: true },
  { formula: '[x] == "A"', values: { x: ["A", "B"] }, expected: false },
  { formula: "[x] == [y]", values: { x: ["A", "B"], y: ["B", "A"] }, expected: true },
  { formula: '[d] == "2026-03-15"', values: { d: "2026.03.15" }, fieldKinds: { d: "date" }, expected: true },
  { formula: '[a] === "x"', values: { a: "x" }, expected: true },
  { formula: "[a] = 3", values: { a: 3 }, expected: true },
  { formula: "[a] <> 3", values: { a: 4 }, expected: true },
  { formula: '[a] !== "x"', values: { a: "x" }, expected: false },
  { formula: "[a] < [b]", values: { a: "10", b: "9" }, expected: false, note: "numeric text orders as numbers" },
  { formula: "[a] < [b]", values: { a: "apple", b: "banana" }, expected: true },
  { formula: "[a] < [b]", values: { a: "15/03/2026", b: "2026-04-01" }, expected: true, note: "date text orders as dates" },
  { formula: "[a] < 5", values: {}, expected: null },
  { formula: '[a] < "abc"', values: { a: 5 }, expected: null },
  { formula: "[a] > 0", values: { a: true }, expected: true },
  { formula: "[a] < [b]", values: { a: "2026-01-01T08:00", b: "2026-01-01T09:00" }, expected: true },
  { formula: "[a] >= 1 && [a] <= 12", values: { a: "12" }, expected: true },

  // ── contains ────────────────────────────────────────────────────────────
  { formula: 'contains("ABC", "b")', expected: true, note: "substring is case-insensitive" },
  { formula: 'contains([m], "B")', values: { m: ["A", "B"] }, expected: true },
  { formula: 'contains([m], "C")', values: { m: ["A", "B"] }, expected: false },
  { formula: 'contains([m], "Beta")', values: { m: [{ code: "B", display: "Beta" }] }, expected: true },
  { formula: 'contains(["often", "very-often"], [q])', values: { q: "often" }, expected: true },
  { formula: 'contains(["often"], [q])', values: {}, expected: false, note: "a blank side is not contained" },
  { formula: 'contains([m], "A")', values: {}, expected: false },
  { formula: 'contains([m], ["C", "A"])', values: { m: ["A"] }, expected: true },
  { formula: 'contains([m], "A")', values: { m: { selectedIds: ["A", "B"], selectedLabels: ["Alpha", "Beta"] } }, expected: true },
  { formula: 'contains([m], "Beta")', values: { m: { selectedItems: [{ code: "A" }, { code: "B", display: "Beta" }] } }, expected: true, note: "FindCodeSelect selections read as their items" },
  { formula: 'contains({"a": 1}, "a")', expected: true },
  { formula: 'contains([x], "Y")', values: { x: { code: "Y", display: "Yes" } }, expected: true },
  {
    formula: '(contains(["often","very-often"], [q1]) ? 1 : 0) + (contains(["often","very-often"], [q2]) ? 1 : 0) + (contains(["often","very-often"], [q3]) ? 1 : 0)',
    values: { q1: "often", q2: "never", q3: "very-often" },
    expected: 2,
  },

  // ── score ───────────────────────────────────────────────────────────────
  { formula: "score(false, 5)", expected: 0 },
  { formula: "score(true)", expected: 1, note: "a checked checkbox scores 1" },
  { formula: "score(false)", expected: 0 },
  { formula: "score([q])", values: { q: "Often" }, scoreMaps: { q: { often: 2, Often: 2 } }, expected: 2 },
  { formula: "score([q])", values: { q: { code: "often", display: "Often" } }, scoreMaps: { q: { Often: 2 } }, expected: 2 },
  { formula: "score([q])", values: { q: { code: "B" } }, scoreMaps: { q: { B: 3, Beta: 3 } }, expected: 3 },
  { formula: 'score([q], {"yes": 4})', values: { q: "YES" }, expected: 4 },
  { formula: "score([q])", values: { q: ["a", "b"] }, scoreMaps: { q: { a: 1, b: 2 } }, expected: 3, note: "a multi-select sums its choices" },
  { formula: "score([q])", values: {}, scoreMaps: { q: { a: 1 } }, expected: null },
  { formula: "score([q]) + score([r])", values: { q: "a" }, scoreMaps: { q: { a: 1 }, r: { a: 1 } }, expected: null },
  { formula: "score([q])", values: { q: "3" }, expected: 3, note: "no map: the answer's own number" },
  { formula: "score([q])", values: { q: "Other" }, scoreMaps: { q: { A: 1 } }, expected: 0, note: "an answered option without a score adds 0" },
  { formula: "score([q])", values: { q: true }, expected: 1 },
  { formula: "score([chk])", values: {}, fieldKinds: { chk: "booleanSingle" }, expected: 0, note: "an untouched single checkbox reads as unchecked" },
  { formula: 'score([q], {"2 to 3 times a week": 3})', values: { q: "2 to 3 times a week" }, expected: 3 },
  { formula: 'score([q], {"None — I do not drink": 0}) + 1', values: { q: "None — I do not drink" }, expected: 1 },
  { formula: 'score([q], {"Y": 2, "N": 0})', values: { q: true }, expected: 2 },
  { formula: "score([q]) + score([r])", values: { q: "a", r: "b" }, scoreMaps: { q: { a: 1 }, r: { b: 2 } }, expected: 3 },

  // ── countTrue ───────────────────────────────────────────────────────────
  { formula: countTrueBuckets, values: { c1: true, c2: "Y", c3: false, c4: true, c5: false }, expected: 2 },
  { formula: "countTrue([a], [b], [c])", values: { a: "yes", b: 1, c: "no" }, expected: 2 },
  { formula: "countTrue([a])", values: {}, expected: 0 },
  { formula: "countTrue([m])", values: { m: [true, "Y", false] }, expected: 2 },
  { formula: "countTrue([a])", values: { a: { code: "Y", display: "Yes" } }, expected: 1 },
  { formula: "countTrue([a], [b])", values: { a: 2, b: "true" }, expected: 1, note: "only 1 counts among numbers" },

  // ── Aggregates ──────────────────────────────────────────────────────────
  { formula: "sum([a], [b], [c])", values: { a: 1, c: 3 }, expected: 4, note: "aggregates skip blanks" },
  { formula: "sum([a], [b])", values: {}, expected: null },
  { formula: "sum([m])", values: { m: ["1", "2", "3"] }, expected: 6 },
  { formula: 'sum([a], "x")', values: { a: 1 }, expected: null },
  { formula: "min([a], [b])", values: { b: 4 }, expected: 4 },
  { formula: "max([a], 3)", values: { a: "7" }, expected: 7 },
  { formula: "max([a], [b])", values: {}, expected: null },
  { formula: "Math.max(1, 5, 3)", expected: 5 },
  { formula: "min([m])", values: { m: ["4", "2"] }, expected: 2 },
  { formula: "MHSUX38 + MHSUX37", values: { MHSUX38: 2 }, dialect: "layoutTable", expected: 2, note: "LayoutTable reads a missing answer as 0" },
  { formula: "sum(q1-a, q1-b, [q1-c])", values: { "q1-a": 1, "q1-c": 2 }, dialect: "layoutTable", expected: 3 },
  { formula: "min(a, b)", values: { b: 4 }, dialect: "layoutTable", expected: 0 },
  { formula: "Math.round(a / 3)", values: { a: 10 }, dialect: "layoutTable", expected: 3 },
  { formula: 'iif(hasValue([allowance]), sum([annual], [allowance]), "")', values: { annual: 1200 }, dialect: "layoutTable", expected: "", note: "A missing required allowance must not read as an entered zero" },
  { formula: 'iif(hasValue([allowance]), sum([annual], [allowance]), "")', values: { annual: 1200, allowance: "" }, dialect: "layoutTable", expected: "" },
  { formula: 'iif(hasValue([allowance]), sum([annual], [allowance]), "")', values: { annual: 1200, allowance: "  " }, dialect: "layoutTable", expected: "" },
  { formula: 'iif(hasValue([allowance]), sum([annual], [allowance]), "")', values: { annual: 1200, allowance: 0 }, dialect: "layoutTable", expected: 1200 },
  { formula: 'iif(hasValue([allowance]), [monthly] * 12 + [allowance], "")', values: { allowance: 0 }, dialect: "layoutTable", expected: 0, note: "Presence guards leave ordinary missing-as-zero arithmetic intact" },

  // ── Numbers ─────────────────────────────────────────────────────────────
  { formula: "round(2.5)", expected: 3 },
  { formula: "round(-2.5)", expected: -2, note: "halves round towards +∞, like Math.round" },
  { formula: "round(1.005, 2)", expected: 1.01, note: "decimal-exact" },
  { formula: "round(1234.5678, -2)", expected: 1200 },
  { formula: "round(3.14159, 3)", expected: 3.142 },
  { formula: "round([a])", values: {}, expected: null },
  { formula: "round(2.345, [d])", values: {}, expected: null },
  { formula: "Math.round(2.4)", expected: 2 },
  { formula: "floor(-1.5)", expected: -2 },
  { formula: "ceil(1.2)", expected: 2 },
  { formula: "ceil(-0.5)", expected: 0 },
  { formula: "trunc(-1.7)", expected: -1 },
  { formula: "abs(-3)", expected: 3 },
  { formula: "mod(7, 3)", expected: 1 },
  { formula: "mod(-7, 3)", expected: -1 },
  { formula: "mod(7, 0)", expected: null },
  { formula: "power(2, 10)", expected: 1024 },
  { formula: "power(-8, 1 / 3)", expected: null },
  { formula: "Math.pow(3, 2)", expected: 9 },
  { formula: "sqrt(16)", expected: 4 },
  { formula: "sqrt(-1)", expected: null },
  { formula: "SQR(9)", expected: 3, note: "Cerner Equation Tool square root" },
  { formula: "ln(1)", expected: 0 },
  { formula: "ln(0)", expected: null },
  { formula: "Log(1)", expected: 0, note: "Cerner Log is the natural log" },
  { formula: "log10(1000)", expected: 3 },
  { formula: "LOG10(0.01)", expected: -2 },
  { formula: "ln(power(1000, 0.4342944819032518))", expected: 3, approx: true, note: "the Cerner importer's LOG10 rewrite" },
  { formula: "exp(0)", expected: 1 },
  { formula: 'number("12.5")', expected: 12.5 },
  { formula: 'number("abc")', expected: null },
  { formula: "Number(true)", expected: 1 },

  // ── Dates (now = 2026-09-26 10:30 local) ────────────────────────────────
  { formula: "today()", expected: "2026-09-26" },
  { formula: "text(today())", expected: "2026-09-26" },
  { formula: 'today() == "2026-09-26"', expected: true },
  { formula: "now() >= today()", expected: true },
  { formula: '[d] < today()', values: { d: "2026-01-01" }, fieldKinds: { d: "date" }, expected: true },
  { formula: 'durationBetween("2026-01-01", "2026-01-11", "days")', expected: 10, note: "date-only inputs count whole calendar days" },
  { formula: 'durationBetween("2026-01-01", "2026-01-11", "weeks")', expected: 10 / 7, approx: true },
  { formula: 'durationBetween("2026-01-15", "2026-03-15", "months")', expected: 2 },
  { formula: 'durationBetween("2026-01-15", "2026-02-01", "month")', expected: 17 / 31, approx: true },
  { formula: 'durationBetween("2026-01-31", "2026-02-28", "months")', expected: 1, note: "month arithmetic clamps to the month's last day" },
  { formula: 'floor(durationBetween("1990-06-15", "2026-06-14", "years"))', expected: 35 },
  { formula: 'floor(durationBetween("1990-06-15", "2026-06-15", "years"))', expected: 36 },
  { formula: 'durationBetween([dob], [end], "days")', values: { dob: "2026-09-20" }, expected: 6, note: "a blank end defaults to today" },
  { formula: "durationBetween([dob])", values: { dob: "2026-09-20" }, expected: 6 },
  { formula: 'durationBetween("2026-01-01", "2026-01-05", "fortnights")', expected: null },
  { formula: 'durationBetween([dob], today(), "years")', values: {}, expected: null },
  { formula: 'durationBetween("2026.03.15", "15/04/2026", "days")', expected: 31, note: "every builder date format parses" },
  { formula: 'durationBetween("03-15-2026", "2026-03-16", "days")', expected: 1 },
  { formula: 'durationBetween("31/04/2026", "2026-05-01")', expected: null, note: "rolled-over dates are invalid" },
  { formula: 'durationBetween("2026-01-02", "2026-01-01", "days")', expected: -1 },
  { formula: 'durationBetween("2026-03-07", "2026-03-09", "days")', expected: 2, note: "across a DST change" },
  { formula: 'durationBetween("2026-03-07T12:00", "2026-03-09T12:00", "days")', expected: 2 },
  { formula: 'durationBetween("2026-01-01T00:00Z", "2026-01-01T12:00Z", "days")', expected: 0.5, note: "exact with a zone" },
  { formula: 'durationText("2026-01-01", "2026-03-20", "months,weeks,days")', expected: "2 months, 2 weeks, 5 days" },
  { formula: 'durationText("2026-01-01", "2026-01-01", "days")', expected: "0 days" },
  { formula: 'durationText("2025-06-15", "2026-09-26")', expected: "1 year, 3 months" },
  { formula: 'durationText([lmp], today(), "weeks,days")', values: { lmp: "2026-02-10" }, expected: "32 weeks, 4 days" },
  { formula: 'durationText("bad", "2026-01-01")', expected: "" },
  { formula: 'durationText("2026-05-01", "2026-01-01", "months")', expected: "0 months", note: "never negative" },
  { formula: 'daysBetween("2026-01-01", "2026-03-01")', expected: 59 },
  { formula: 'daysBetween("2026-01-01T23:00", "2026-01-02T01:00")', expected: 1, note: "times of day ignored" },
  { formula: 'daysBetween("2026-09-20")', expected: 6 },
  { formula: 'daysBetween("2026-09-20", [x])', values: {}, expected: null },
  { formula: 'monthsBetween("2026-01-31", "2026-03-01")', expected: 1 },
  { formula: "daysSince([d], [r])", values: { d: "2026-01-01", r: "2026-01-10" }, expected: 9 },
  { formula: "daysSince([d])", values: { d: "2026-09-20" }, expected: 6 },
  { formula: 'daysSince("2026-01-01T12:00", "2026-01-02T11:00")', expected: 0, note: "completed 24-hour days with a time" },
  { formula: 'floor(daysSince([ga], [form]) / 7)', values: { ga: "2026.08.01", form: "2026.09.19" }, expected: 7 },
  { formula: 'mod(daysSince([ga], [form]), 7)', values: { ga: "2026.08.01", form: "2026.09.19" }, expected: 0 },
  { formula: 'monthsSince("2026-06-26")', expected: 3 },
  { formula: 'monthsSince("2026-06-27")', expected: 2 },
  { formula: "monthsSince([d]) >= 0 && monthsSince([d]) < 3", values: { d: "2026-08-01" }, expected: true },
  // dateAdd(): FHIRPath calendar-duration arithmetic (https://hl7.org/fhirpath/#datetime-arithmetic)
  { formula: 'dateAdd("2024-01-31", 1, "months")', expected: "2024-02-29", note: "a day the month lacks becomes its last day" },
  { formula: 'dateAdd("2024-03-31", -1, "month")', expected: "2024-02-29" },
  { formula: 'dateAdd("2024-02-29", 1, "years")', expected: "2025-02-28" },
  { formula: 'dateAdd("2024-01-31", 13, "months")', expected: "2025-02-28", note: "months carry into years" },
  { formula: 'dateAdd("2024-01-31", 2, "weeks")', expected: "2024-02-14" },
  { formula: 'dateAdd("2024-01-31", 1.7, "days")', expected: "2024-02-01", note: "the decimal part is ignored" },
  { formula: 'dateAdd("2024-12-31", -365, "days")', expected: "2024-01-01" },
  { formula: 'dateAdd([d], -18, "years")', values: { d: "2026-09-26" }, fieldKinds: { d: "date" }, expected: "2008-09-26" },
  { formula: 'dateAdd(today(), -12, "months")', expected: "2025-09-26" },
  { formula: 'dateAdd(now(), -2, "years") < now()', expected: true },
  { formula: 'text(dateAdd("2026-03-07T12:00", 1, "days"))', expected: new Date(2026, 2, 8, 12, 0).toISOString(), note: "the wall-clock time is kept across a DST change" },
  { formula: '[d] > dateAdd(now(), -2, "years")', values: { d: "2025-01-15" }, fieldKinds: { d: "date" }, expected: true },
  { formula: '[d] > dateAdd(now(), -2, "years")', values: { d: "2024-01-15" }, fieldKinds: { d: "date" }, expected: false },
  { formula: 'dateAdd([d], 1, "days")', values: {}, expected: null },
  { formula: 'dateAdd("2026-01-01", [n], "days")', values: {}, expected: null },
  { formula: 'dateAdd("2026-01-01", 1, "fortnights")', expected: null },

  // substring(), upper(), lower(): FHIRPath string functions
  { formula: 'substring("abcdefg", 3)', expected: "defg" },
  { formula: 'substring("abcdefg", 1, 2)', expected: "bc" },
  { formula: 'substring("abcdefg", 6, 2)', expected: "g" },
  { formula: 'substring("abcdefg", 7, 1)', expected: null, note: "a start outside the text is blank" },
  { formula: 'substring("abcdefg", -1, 1)', expected: null },
  { formula: 'substring("abcdefg", 3, 0)', expected: null, note: "FHIRPath gives '', which reads as blank" },
  { formula: 'substring("abcdefg", 3, [n])', values: {}, expected: "defg", note: "a blank length reads to the end" },
  { formula: 'substring([t], 0, 1)', values: {}, expected: null },
  { formula: 'substring(text(today()), 0, 4)', expected: "2026" },
  { formula: 'substring("héllo😀x", 4, 2)', expected: "o😀", note: "counted in characters" },
  { formula: 'upper("Smith")', expected: "SMITH" },
  { formula: 'lower("SmItH")', expected: "smith" },
  { formula: "upper([t])", values: {}, expected: null },
  // replaceMatches(): FHIRPath, JavaScript regular expressions (regex.ts)
  { formula: 'replaceMatches("O\'Brien-Smith", "[^A-Za-z]", "")', expected: "OBrienSmith", note: "the SLK strips everything but letters" },
  { formula: 'substring(replaceMatches([family], "[^A-Za-z]", ""), 4, 1)', values: { family: "Li" }, expected: null, note: "a short name has no fifth letter: the SLK pads with 2" },
  { formula: 'coalesce(substring(replaceMatches([family], "[^A-Za-z]", ""), 1, 1), "2")', values: { family: "O'Neill" }, expected: "N" },
  { formula: 'replaceMatches("11/30/1972", "(\\\\d+)/(\\\\d+)/(\\\\d+)", "$2-$1-$3")', expected: "30-11-1972" },
  { formula: 'replaceMatches("11/30/1972", "(?<m>\\\\d+)/(?<d>\\\\d+)", "$<d>.$<m>")', expected: "30.11/1972", note: "named groups are $<name>; FHIRPath's ${name} is literal, as in fhirpath.js" },
  { formula: 'replaceMatches("a\\nb", "a.b", "x")', expected: "x", note: "single-line mode: . matches a line break" },
  { formula: 'replaceMatches("abc", "B", "x")', expected: "abc", note: "case-sensitive" },
  { formula: 'replaceMatches("--", "-", "")', expected: null, note: "an empty result is blank" },
  { formula: 'replaceMatches("abc", "b", [s])', values: {}, expected: "ac", note: "a blank substitution removes the matches" },
  { formula: 'replaceMatches([t], "b", "x")', values: {}, expected: null },
  { formula: 'replaceMatches("abc", [p], "x")', values: {}, expected: null },
  { formula: 'replaceMatches("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa!", "(a+)+$", "x")', expected: null, note: "a pattern that can backtrack catastrophically is refused" },
  { formula: 'replaceMatches("abc", "[", "x")', expected: null, note: "an invalid pattern is blank" },
  { formula: "weekdaysBetween([from], [to])", values: { from: "2026-10-05", to: "2026-10-09" }, expected: 5 },
  { formula: "weekdaysBetween([from], [to])", values: { from: "2026.10.05", to: "2026.10.16" }, expected: 10 },
  { formula: "weekdaysBetween([from], [to])", values: { from: "2026-10-05", to: "2026-10-05" }, expected: 1 },
  { formula: "weekdaysBetween([from], [to])", values: { from: "2026-10-10", to: "2026-10-11" }, expected: 0 },
  { formula: 'weekdaysBetween([from], [to], "2026-10-12")', values: { from: "2026-10-09", to: "2026-10-13" }, expected: 2 },
  {
    formula: 'weekdaysBetween([from], [to], ["2026-12-25", "2026-12-26", "2026-12-28", "2027-01-01", "2027-01-01"])',
    values: { from: "2026-12-24", to: "2027-01-04" },
    expected: 5,
  },
  { formula: 'weekdaysBetween([from], [to], "2026-12-25, 2027-01-01")', values: { from: "2026-12-24", to: "2027-01-04" }, expected: 6 },
  { formula: "weekdaysBetween([from], [to])", values: { from: "2026-10-09", to: "2026-10-05" }, expected: null },
  { formula: "weekdaysBetween([from], [to])", values: { from: "2026-10-05", to: "" }, expected: null },
  { formula: 'ageYears("1990-09-27")', expected: 35 },
  { formula: 'ageYears("1990-09-26")', expected: 36 },
  { formula: "ageYears([dob], [asOf])", values: { dob: "2000-01-01" }, expected: 26 },
  { formula: "text([d])", values: { d: "2026-03-15" }, fieldKinds: { d: "date" }, expected: "2026-03-15", note: "date-only is a local calendar date" },
  { formula: "[d]", values: { d: new Date(2026, 2, 15, 13, 0) }, fieldKinds: { d: "date" }, expected: "2026-03-15" },
  { formula: "[d]", values: { d: { date: "2026-03-15" } }, expected: "2026-03-15" },
  { formula: "[d]", values: { d: "2026.03.15 10:30" }, fieldKinds: { d: "datetime" }, expected: new Date(2026, 2, 15, 10, 30).toISOString(), note: "a DateSelect format with a time is local time" },
  { formula: "[d]", values: { d: "2026-03-15T17:30:00.000Z" }, fieldKinds: { d: "datetime" }, expected: "2026-03-15T17:30:00.000Z", note: "DateTimeSelect stores ISO 8601 UTC" },
  { formula: 'durationBetween("5", "2026-01-01")', expected: null, note: "numeric text is never a date" },

  // ── Clinical ────────────────────────────────────────────────────────────
  { formula: "bmi(70, 175)", expected: 70 / 3.0625 },
  { formula: "bmi(0, 175)", expected: null },
  { formula: "bmi([w], [h])", values: { h: 175 }, expected: null },
  { formula: "round([w] / power([h] / 100, 2), 1)", values: { w: 70, h: 175 }, expected: 22.9 },
  { formula: "hasValue([w]) && hasValue([h]) && [h] > 0 ? (10000 * [w]) / ([h] * [h]) : null", values: { w: 70, h: 175 }, expected: (10000 * 70) / (175 * 175) },
  { formula: 'zScore({"x": 1})', expected: null, note: "blank without a host implementation" },

  // ── Conditionals from shipped forms ─────────────────────────────────────
  { formula: suicideRisk, values: { q1: "No" }, expected: "LOW" },
  { formula: suicideRisk, values: { q1: "Yes", q2: "No" }, expected: "LOW" },
  { formula: suicideRisk, values: { q1: "Yes", q2: "Yes", q3: "Yes" }, expected: "HIGH" },
  { formula: suicideRisk, values: { q1: "Yes", q2: "Yes", q3: "No", q4: "No", q5: "No", q6: "Yes" }, expected: "HIGH" },
  { formula: suicideRisk, values: { q1: "Yes", q2: "Yes", q3: "No", q4: "No", q5: "No", q6: "No" }, expected: "MODERATE" },
  { formula: idealBodyWeight, values: { sex: "F", height: 165 }, expected: 45.5 + 2.3 * (165 / 2.54 - 60) },
  { formula: idealBodyWeight, values: { sex: { code: "M", display: "Male" }, height: 180 }, expected: 50 + 2.3 * (180 / 2.54 - 60) },
  { formula: idealBodyWeight, values: { height: 180 }, expected: null },
  { formula: correctedWeeks, values: { x: 15 }, expected: 2 },
  { formula: correctedWeeks, values: { x: 0 }, expected: "N/A" },
  { formula: correctedWeeks, values: { x: "N/A" }, expected: "N/A" },
  { formula: pediatricWeight, values: { a: 6 }, expected: 7 },
  { formula: pediatricWeight, values: { a: 24 }, expected: 12 },
  { formula: pediatricWeight, values: { a: 200 }, expected: null },
  { formula: "coalesce([a], 0) + [b]", values: { b: 2 }, expected: 2, note: "a Cerner optional component defaults to 0" },
  {
    formula: 'iif(([prev] == "Yes" || [prev] == "Y") && hasValue([date]) && monthsSince([date]) >= 0 && monthsSince([date]) < 3, "Y", "N")',
    values: { prev: { code: "Y", display: "Yes" }, date: "2026-08-15" },
    expected: "Y",
  },
  {
    formula: 'iif(([prev] == "Yes" || [prev] == "Y") && hasValue([date]) && monthsSince([date]) >= 0 && monthsSince([date]) < 3, "Y", "N")',
    values: { prev: "No" },
    expected: "N",
  },

  // ── Literals, reads and templates ───────────────────────────────────────
  { formula: "[1, 2, 3]", expected: [1, 2, 3] },
  { formula: '["a", null, "b"]', expected: ["a", "b"] },
  { formula: '{"a": 1}', expected: { a: 1 } },
  { formula: "[]", expected: null },
  { formula: "[x]", values: { x: { code: "Y", display: "Yes" } }, expected: "Y", note: "a choice's result is its code" },
  { formula: "[x]", values: { x: { selectedKey: "3", response: "Three" } }, expected: "3" },
  { formula: "[x]", values: { x: "  hi  " }, expected: "hi" },
  { formula: "[x]", values: { x: ["a", "", "b"] }, expected: ["a", "b"] },
  { formula: "[x]", values: { x: { selectedIds: ["a"], selectedLabels: ["Alpha"] } }, expected: ["a"] },
  { formula: "[x]", values: { x: { selectedItem: { code: "Y", display: "Yes" } } }, expected: "Y" },
  { formula: "[x]", values: { x: { selectedItems: [{ code: "a" }, { code: "b" }] } }, expected: ["a", "b"] },
  { formula: "hasValue([x])", values: { x: { selectedItems: [] } }, expected: false },
  { formula: 'score([x], {"b": 2, "c": 3})', values: { x: { selectedItems: [{ code: "b" }, { code: "c" }] } }, expected: 5 },
  { formula: "[b]", values: { b: "Y" }, fieldKinds: { b: "booleanYesNo" }, expected: true },
  { formula: "[b]", values: { b: { code: "N", display: "No", system: "MOIS-YESNO" } }, fieldKinds: { b: "booleanYesNo" }, expected: false },
  { formula: "[b]", values: {}, fieldKinds: { b: "booleanSingle" }, expected: false },
  { formula: "{weight} / power({height} / 100, 2)", params: { weight: 70, height: 175 }, expected: 70 / 3.0625 },
  { formula: "({0} - {1}) / 3 + {1}", params: { "0": 120, "1": 80 }, expected: (120 - 80) / 3 + 80 },
  { formula: chartName, params: { "patient.name.first": "Ann", "patient.nickName.text": "Annie" }, dialect: "chartValue", expected: "Ann (Annie)" },
  { formula: chartName, params: { "patient.name.first": "Ann" }, dialect: "chartValue", expected: "Ann" },
  { formula: "Math.PI > 3.14", expected: true },

  // ── Stored shapes, read by values.ts (readBoolean, readChoice, readDateTime) ──
  { formula: "[x] == true", values: { x: "checked" }, expected: true, note: "yes/no words are values.ts readBoolean's" },
  { formula: "countTrue([a], [b])", values: { a: "on", b: "off" }, expected: 1 },
  { formula: 'iif([t], "yes", "no")', values: { t: "unchecked" }, expected: "no" },
  { formula: "[x]", values: { x: { coding: [{ system: "http://loinc.org", code: "LA33-6", display: "Yes" }], text: "Yes" } }, expected: "LA33-6", note: "a FHIR CodeableConcept reads as its first coding" },
  { formula: '[x] == "Yes"', values: { x: { valueCoding: { code: "LA33-6", display: "Yes" } } }, expected: true },
  { formula: "[x]", values: { x: { id: "o1", label: "Other" } }, expected: "o1", note: "code precedence: selectedKey, else code, value, key, id" },
  { formula: "text([x])", values: { x: { key: "routine", response: "Routine", text: "Routine visit" } }, expected: "Routine", note: "label precedence: display, response, label, text" },
  { formula: "[x] + 1", values: { x: { value: { code: "3", display: "Three" } } }, expected: 4, note: "a { value } wrapper reads as what it wraps" },
  { formula: "text([m])", values: { m: { selectedLabels: ["Alpha", "Beta"] } }, expected: "Alpha, Beta", note: "checklist labels without ids" },
  { formula: '[s] == "9"', values: { s: { selectedKey: "9", value: 0, response: "Unknown" } }, expected: true },
  { formula: "[s] == 0", values: { s: { selectedKey: "9", value: 0, response: "Unknown" } }, expected: true, note: "a selection's scalar value is a further match key" },
  { formula: "[s] + 0", values: { s: { selectedKey: "9", value: 0, response: "Unknown" } }, expected: 9, note: "arithmetic reads the code first" },

  // ── incomplete: "compute-anyway" (missing field answers count as 0) ──────
  { formula: "[a] + [b]", values: { a: 2 }, incomplete: "compute-anyway", expected: 2 },
  { formula: "[a] + [b]", values: {}, incomplete: "compute-anyway", expected: 0 },
  { formula: "score([q1]) + score([q2])", values: { q1: "a" }, scoreMaps: { q1: { a: 1 }, q2: { a: 1 } }, incomplete: "compute-anyway", expected: 1, note: "a partial total" },
  { formula: "score([q1], {\"a\": 2})", values: {}, incomplete: "compute-anyway", expected: 0 },
  { formula: "[w] / power([h] / 100, 2)", values: { w: 70 }, incomplete: "compute-anyway", expected: null, note: "a missing height divides by zero" },
  { formula: 'iif([s] >= 10, "Positive", "Negative")', values: {}, incomplete: "compute-anyway", expected: "Negative" },
  { formula: 'iif([flag], "on", "off")', values: {}, incomplete: "compute-anyway", expected: "off" },
  { formula: "hasValue([a])", values: {}, incomplete: "compute-anyway", expected: false },
  { formula: "coalesce([a], 5)", values: {}, incomplete: "compute-anyway", expected: 5 },
  { formula: 'concat("x", [a])', values: {}, incomplete: "compute-anyway", expected: "x" },
  { formula: "[a] == 0", values: {}, incomplete: "compute-anyway", expected: false, note: "equality still reads it as blank" },
  { formula: "sum([a], [b])", values: {}, incomplete: "compute-anyway", expected: null, note: "aggregates skip it" },
  { formula: 'durationBetween([dob], today(), "years")', values: {}, incomplete: "compute-anyway", expected: null, note: "dates never count as 0" },
  { formula: "[a]", values: {}, incomplete: "compute-anyway", expected: null },
  { formula: "round([a] / 3, 1) + 1", values: { a: 5 }, incomplete: "compute-anyway", expected: 2.7, note: "answered inputs are unaffected" },

  // ── latest(): the patient's latest charted result ───────────────────────
  { formula: 'latest({"loinc": "29463-7"})', observations: CHART, expected: 72.5, note: "the latest counted result; numeric text reads as a number; entered-in-error never counts" },
  { formula: 'latest({"mois": "22732"}) * 2', observations: CHART, expected: 145, note: "a MOIS observation code" },
  { formula: 'latest({"loinc": "29463-7"}, {"withinMinutes": 60})', observations: CHART, expected: null, note: "nothing in the look-back window: blank" },
  { formula: 'latest({"loinc": "29463-7"}, {"withinMinutes": 2880})', observations: CHART, expected: 72.5 },
  { formula: 'latest({"loinc": "29463-7"}, {"withinMinutes": 60, "fallback": 0})', observations: CHART, expected: 0 },
  { formula: 'latest({"loinc": "29463-7"}, {"withinMinutes": 60}) + 1', observations: CHART, expected: null, note: "a missing result blanks the formula" },
  { formula: 'latest({"loinc": "29463-7"}, {"withinMinutes": 60}) + 1', observations: CHART, incomplete: "compute-anyway", expected: 1, note: "and counts as 0 when calculating from what is there" },
  { formula: 'latest({"loinc": "29463-7", "unit": "lb"})', observations: CHART, expected: null, note: "a result in another unit does not count" },
  { formula: 'latest({"loinc": "8867-4"})', observations: CHART, expected: 90, note: "every status counts by default, a preliminary one included" },
  { formula: 'latest({"loinc": "8867-4"}, {"statuses": ["final", "amended", "corrected"]})', observations: CHART, expected: 88 },
  { formula: 'latest("http://loinc.org|8867-4")', observations: CHART, expected: 90, note: "the FHIR token form" },
  { formula: 'latest({"dta": "RASS Score"})', observations: CHART, expected: -2, note: "a Cerner DTA by its mnemonic (the record's label or a domain DTA coding)" },
  { formula: 'latest({"mois": "SMOKE"})', observations: CHART, expected: "Never smoker", note: "a text result stays text" },
  { formula: 'latest({"loinc": "1111-1"})', observations: CHART, expected: null, note: "a result after now does not count" },
  { formula: 'latest({"loinc": "1111-1"}, {"aheadMinutes": 60})', observations: CHART, expected: 5, note: "unless it is inside the look-ahead" },
  { formula: 'latest({"loinc": "0000-0"}, {"fallback": [w]})', values: { w: 5 }, observations: CHART, expected: 5, note: "the fallback is any formula" },
  { formula: 'hasValue(latest({"loinc": "0000-0"}))', observations: CHART, expected: false },
  { formula: 'latest({"loinc": "29463-7"})', expected: null, note: "no chart: no result" },

  // Chart facts read as references (formula/chart-facts.ts): the host answers them from the chart.
  { formula: 'dateAdd([chart:patient.birthDate], 18, "years") <= today()', values: { "chart:patient.birthDate": "2008-09-26" }, expected: true, note: "the birth date reads as a date without a field kind" },
  { formula: 'dateAdd([chart:patient.birthDate], 18, "years") <= today()', values: { "chart:patient.birthDate": "2008-09-27" }, expected: false },
  { formula: '[d] > dateAdd([chart:patient.birthDate], 18, "years")', values: { d: "2026-09-01", "chart:patient.birthDate": "2000-01-01" }, fieldKinds: { d: "date" }, expected: true },
  { formula: '[chart:patient.sex] == "female"', values: { "chart:patient.sex": "female" }, expected: true },
  { formula: '[chart:patient.ageYears] >= 65', values: { "chart:patient.ageYears": 70 }, expected: true },
  { formula: '[chart:patient.concept.DIABETES] == "yes"', values: {}, expected: false, note: "a chart without the fact reads blank" },
];
