import "./moment-locale";
import { TERRA_MESSAGES } from "./terra-messages";

import React from "react";

import { hoistStatics } from "./hoist-statics";

/**
 * Minimal stand-in for the parts of `react-intl` Terra uses.
 *
 * Terra's intl surface is shallow — `FormattedMessage` for a handful of
 * literals (e.g. the "(optional)" suffix) and `injectIntl` to hand
 * components an `intl.formatMessage` for accessibility labels. Shimming it
 * removes the dependency entirely, which matters because Terra's peer range
 * (react-intl 2-5) tops out below React 18 and cannot be satisfied here.
 *
 * Translations default to Terra's own en-CA strings; pass `messages` to
 * TerraIntlProvider to localise.
 */

/**
 * Terra's own strings for DEFAULT_LOCALE, generated by scripts/vendor.mjs from
 * each vendored package's `translations/`. Generated rather than hand-written
 * because a hand-written map covers only the components someone remembered:
 * DemographicsBanner asks for ten ids, and the old map had one — so the banner
 * printed `Terra.demographicsBanner.dateOfBirth` on screen.
 */
export const DEFAULT_MESSAGES: Record<string, string> = TERRA_MESSAGES;

export interface TerraIntl {
  /** BCP 47 tag; the date picker reads it to pick a calendar locale. */
  locale: string;
  formatMessage(descriptor: { id: string }, values?: Record<string, unknown>): string;
}

interface IntlValue {
  locale: string;
  messages: Record<string, string>;
}

// terra-date-picker derives its input mask and placeholder from moment's
// locale data for `intl.locale`. moment bundles only `en`, and an unregistered
// locale falls back to it silently — which is why an unconfigured date field
// renders US order (MM/DD/YYYY) rather than the YYYY-MM-DD used in BC.
const DEFAULT_LOCALE = "en-CA";


const IntlContext = React.createContext<IntlValue>({
  locale: DEFAULT_LOCALE,
  messages: DEFAULT_MESSAGES,
});

export const TerraIntlProvider: React.FC<{
  locale?: string;
  messages?: Record<string, string>;
  children?: React.ReactNode;
}> = ({ locale, messages, children }) => {
  const value = React.useMemo(
    () => ({ locale: locale ?? DEFAULT_LOCALE, messages: { ...DEFAULT_MESSAGES, ...messages } }),
    [locale, messages],
  );
  return <IntlContext.Provider value={value}>{children}</IntlContext.Provider>;
};

/**
 * ICU messages in Terra's translations only ever use simple `{name}`
 * placeholders — no plural/select forms — so substitution is enough.
 */
function format(messages: Record<string, string>, id: string, values?: Record<string, unknown>): string {
  const template = messages[id] ?? id;
  if (!values) return template;
  return template.replace(/\{(\w+)\}/g, (match, key: string) =>
    key in values ? String(values[key]) : match,
  );
}

export const FormattedMessage: React.FC<{
  id: string;
  values?: Record<string, unknown>;
  children?: (formatted: string) => React.ReactNode;
}> = ({ id, values, children }) => {
  const { messages } = React.useContext(IntlContext);
  const text = format(messages, id, values);
  return <>{typeof children === "function" ? children(text) : text}</>;
};

/** Terra components receive `intl` as a prop; mirror that shape. */
export function injectIntl<P extends { intl?: TerraIntl }>(
  Component: React.ComponentType<P>,
): React.ComponentType<Omit<P, "intl">> {
  const Wrapped = (props: Omit<P, "intl">) => {
    const { locale, messages } = React.useContext(IntlContext);
    const intl: TerraIntl = React.useMemo(
      () => ({
        locale,
        formatMessage: (descriptor, values) => format(messages, descriptor.id, values),
      }),
      [locale, messages],
    );
    return React.createElement(Component, { ...(props as P), intl });
  };
  Wrapped.displayName = `injectIntl(${Component.displayName || Component.name || "Component"})`;
  // react-intl hoists non-React statics here; Terra relies on it for
  // `SingleSelect.Option` and friends.
  return hoistStatics(Wrapped, Component);
}

export const intlShape = {};
