/**
 * Shared case table for values.ts and its NHForms twin ValueKit
 * (packages/form-components/src/nhforms/__tests__/value-kit-parity.test.ts).
 * Every stored shape found in data/ fixtures and the NHForms runtimes has a
 * case here; add new shapes here so both implementations are held to them.
 */

export type ValueCase =
  | { name: string; fn: "normalizeOption"; args: [unknown]; expected: unknown }
  | { name: string; fn: "readBoolean"; args: [unknown] | [unknown, unknown]; expected: boolean | null }
  | { name: string; fn: "readChoice"; args: [unknown] | [unknown, unknown]; expected: unknown[] }
  | { name: string; fn: "readDate"; args: [unknown]; expected: Date | null };

const ORDINAL_URL = "http://hl7.org/fhir/StructureDefinition/ordinalValue";
const COUNTRIES = [{ label: "Australia", value: "AU" }, { label: "Canada", value: "CA" }];

export const NORMALIZE_OPTION_CASES: ValueCase[] = [
  { name: "bare string", fn: "normalizeOption", args: ["Yes"], expected: { code: "Yes", display: "Yes" } },
  { name: "bare number (panel library)", fn: "normalizeOption", args: [0], expected: { code: "0", display: "0" } },
  { name: "null", fn: "normalizeOption", args: [null], expected: { code: "", display: "" } },
  { name: "builder { label, value }", fn: "normalizeOption", args: [{ label: "Australia", value: "AU" }], expected: { code: "AU", display: "Australia" } },
  { name: "builder { label } only", fn: "normalizeOption", args: [{ label: "Ready for use" }], expected: { code: "Ready for use", display: "Ready for use" } },
  { name: "builder blank value falls back to label", fn: "normalizeOption", args: [{ label: "X", value: "" }], expected: { code: "X", display: "X" } },
  { name: "builder { label, value, score }", fn: "normalizeOption", args: [{ label: "Not at all", value: "0", score: 0 }], expected: { code: "0", display: "Not at all", score: 0 } },
  { name: "builder score as numeric text", fn: "normalizeOption", args: [{ label: "Moderate", score: "2" }], expected: { code: "Moderate", display: "Moderate", score: 2 } },
  { name: "builder non-finite score dropped", fn: "normalizeOption", args: [{ label: "Yes", value: "Y", score: Number.NaN }], expected: { code: "Y", display: "Yes" } },
  { name: "builder presentation metadata ignored", fn: "normalizeOption", args: [{ label: "1", hotKey: "1", order: 1 }], expected: { code: "1", display: "1" } },
  { name: "Cerner nomenclature option", fn: "normalizeOption", args: [{ label: "0 - Hematology slide", cernerNomenclatureId: "11491124" }], expected: { code: "0 - Hematology slide", display: "0 - Hematology slide" } },
  { name: "dform { label, state, score }", fn: "normalizeOption", args: [{ label: "Mild", state: "1", score: 1 }], expected: { code: "1", display: "Mild", score: 1 } },
  { name: "scoring { id, label, score }", fn: "normalizeOption", args: [{ id: "none", label: "None", score: 0 }], expected: { code: "none", display: "None", score: 0 } },
  { name: "coded { code, display }", fn: "normalizeOption", args: [{ code: "contactParentClient", display: "Contact to Parent/Client" }], expected: { code: "contactParentClient", display: "Contact to Parent/Client" } },
  { name: "coded { code, text }", fn: "normalizeOption", args: [{ code: "Yes", text: "Full" }], expected: { code: "Yes", display: "Full" } },
  { name: "coded { key, text }", fn: "normalizeOption", args: [{ key: "routine", text: "Routine" }], expected: { code: "routine", display: "Routine" } },
  { name: "coded { key, text, value }", fn: "normalizeOption", args: [{ key: "A", text: "Alpha", value: "A" }], expected: { code: "A", display: "Alpha" } },
  { name: "coded { text } only", fn: "normalizeOption", args: [{ text: "Only text" }], expected: { code: "Only text", display: "Only text" } },
  { name: "Coding with system", fn: "normalizeOption", args: [{ code: "Y", display: "Yes", system: "MOIS-YESNO" }], expected: { code: "Y", display: "Yes", system: "MOIS-YESNO" } },
  { name: "import target metadata ignored", fn: "normalizeOption", args: [{ code: "str_field_21002", display: "Public Health Nurse", target: { fieldId: "s1101", mode: "yesNo" } }], expected: { code: "str_field_21002", display: "Public Health Nurse" } },
  { name: "subform { id, key, label, value, system }", fn: "normalizeOption", args: [{ id: "o1", key: "k1", label: "Label", value: "v1", system: "SYS" }], expected: { code: "v1", display: "Label", system: "SYS" } },
  { name: "scale { value, label }", fn: "normalizeOption", args: [{ value: 0, label: "0", description: "None" }], expected: { code: "0", display: "0", score: 0 } },
  { name: "scale key differs from score (HoNOS 9)", fn: "normalizeOption", args: [{ value: 0, label: "Unknown", key: "9" }], expected: { code: "9", display: "Unknown", score: 0 } },
  { name: "EditableTable checkbox option", fn: "normalizeOption", args: [{ key: "true", value: 1, text: "Checked" }], expected: { code: "true", display: "Checked", score: 1 } },
  { name: "numeric value with explicit score", fn: "normalizeOption", args: [{ value: 3, label: "Three", score: 6 }], expected: { code: "3", display: "Three", score: 6 } },
  {
    name: "FHIR answerOption with ordinalValue",
    fn: "normalizeOption",
    args: [{ extension: [{ url: ORDINAL_URL, valueDecimal: 1 }], valueCoding: { code: "no-effect", display: "No effect" } }],
    expected: { code: "no-effect", display: "No effect", score: 1 },
  },
  {
    name: "FHIR answerOption with system",
    fn: "normalizeOption",
    args: [{ valueCoding: { system: "http://hl7.org/fhir/administrative-gender", code: "male", display: "Male" } }],
    expected: { code: "male", display: "Male", system: "http://hl7.org/fhir/administrative-gender" },
  },
  { name: "FHIR valueString", fn: "normalizeOption", args: [{ valueString: "Other" }], expected: { code: "Other", display: "Other" } },
  { name: "FHIR valueInteger", fn: "normalizeOption", args: [{ valueInteger: 4 }], expected: { code: "4", display: "4" } },
];

const YES_NO_LABELS = { on: "Present", off: "Absent" };

export const READ_BOOLEAN_CASES: ValueCase[] = [
  { name: "true", fn: "readBoolean", args: [true], expected: true },
  { name: "false", fn: "readBoolean", args: [false], expected: false },
  { name: "null", fn: "readBoolean", args: [null], expected: null },
  { name: "undefined", fn: "readBoolean", args: [undefined], expected: null },
  { name: "1", fn: "readBoolean", args: [1], expected: true },
  { name: "0", fn: "readBoolean", args: [0], expected: false },
  { name: "2 is not a yes/no", fn: "readBoolean", args: [2], expected: null },
  { name: "'true'", fn: "readBoolean", args: ["true"], expected: true },
  { name: "'FALSE'", fn: "readBoolean", args: ["FALSE"], expected: false },
  { name: "'Yes'", fn: "readBoolean", args: ["Yes"], expected: true },
  { name: "' no '", fn: "readBoolean", args: [" no "], expected: false },
  { name: "'Y'", fn: "readBoolean", args: ["Y"], expected: true },
  { name: "'n'", fn: "readBoolean", args: ["n"], expected: false },
  { name: "'1'", fn: "readBoolean", args: ["1"], expected: true },
  { name: "'0'", fn: "readBoolean", args: ["0"], expected: false },
  { name: "'on' (PDF checkbox)", fn: "readBoolean", args: ["on"], expected: true },
  { name: "'Off' (PDF checkbox)", fn: "readBoolean", args: ["Off"], expected: false },
  { name: "'Checked' (older table rows)", fn: "readBoolean", args: ["Checked"], expected: true },
  { name: "'Unchecked'", fn: "readBoolean", args: ["Unchecked"], expected: false },
  { name: "'X' tick mark", fn: "readBoolean", args: ["X"], expected: true },
  { name: "empty text", fn: "readBoolean", args: [""], expected: null },
  { name: "other text", fn: "readBoolean", args: ["maybe"], expected: null },
  { name: "MOIS-YESNO Y", fn: "readBoolean", args: [{ code: "Y", display: "Yes", system: "MOIS-YESNO" }], expected: true },
  { name: "MOIS-YESNO N", fn: "readBoolean", args: [{ code: "N", display: "No", system: "MOIS-YESNO" }], expected: false },
  { name: "code wins over display", fn: "readBoolean", args: [{ code: "N", display: "Yes" }], expected: false },
  { name: "unknown Coding", fn: "readBoolean", args: [{ code: "UNK", display: "Unknown", system: "MOIS-YNU" }], expected: null },
  { name: "Coding with label-only display", fn: "readBoolean", args: [{ code: "A1", display: "Yes" }], expected: true },
  { name: "subform checkbox selected", fn: "readBoolean", args: [{ selectedKey: "true", value: 1, response: "Checked", detailResponse: "Checked" }], expected: true },
  { name: "subform checkbox cleared", fn: "readBoolean", args: [{ selectedKey: "false", value: 0, response: "Unchecked" }], expected: false },
  { name: "subform unanswered", fn: "readBoolean", args: [{ selectedKey: null, value: null, response: null }], expected: null },
  { name: "subform yes/no by label", fn: "readBoolean", args: [{ selectedKey: "Yes", value: "Yes", response: "Yes" }], expected: true },
  { name: "{ value } wrapper", fn: "readBoolean", args: [{ value: true }], expected: true },
  { name: "{ value: 'no' } wrapper", fn: "readBoolean", args: [{ value: "no" }], expected: false },
  { name: "{ key, text } option", fn: "readBoolean", args: [{ key: "yes", text: "Yes" }], expected: true },
  { name: "one-element array", fn: "readBoolean", args: [[{ code: "Y" }]], expected: true },
  { name: "empty array", fn: "readBoolean", args: [[]], expected: null },
  { name: "several answers", fn: "readBoolean", args: [["Y", "N"]], expected: null },
  { name: "custom on label", fn: "readBoolean", args: ["Present", YES_NO_LABELS], expected: true },
  { name: "custom off label", fn: "readBoolean", args: ["absent", YES_NO_LABELS], expected: false },
  { name: "custom label without labels", fn: "readBoolean", args: ["Present"], expected: null },
  { name: "built-in text with custom labels", fn: "readBoolean", args: ["yes", YES_NO_LABELS], expected: true },
  { name: "custom label in a selection", fn: "readBoolean", args: [{ selectedKey: "p", response: "Present" }, YES_NO_LABELS], expected: true },
];

export const READ_CHOICE_CASES: ValueCase[] = [
  { name: "null", fn: "readChoice", args: [null], expected: [] },
  { name: "empty text", fn: "readChoice", args: [""], expected: [] },
  { name: "blank text", fn: "readChoice", args: ["  "], expected: [] },
  { name: "bare code", fn: "readChoice", args: ["AU"], expected: [{ code: "AU" }] },
  { name: "number", fn: "readChoice", args: [3], expected: [{ code: "3" }] },
  { name: "array of codes", fn: "readChoice", args: [["a", "b"]], expected: [{ code: "a" }, { code: "b" }] },
  { name: "empty array", fn: "readChoice", args: [[]], expected: [] },
  {
    name: "Coding",
    fn: "readChoice",
    args: [{ code: "E2E-ALPHA", display: "E2E Alpha", system: "E2E-VALIDATION" }],
    expected: [{ code: "E2E-ALPHA", display: "E2E Alpha", system: "E2E-VALIDATION" }],
  },
  {
    name: "array of Codings",
    fn: "readChoice",
    args: [[{ code: "HCW1", display: "Direct Care", system: "C19" }, { code: "HCW2" }]],
    expected: [{ code: "HCW1", display: "Direct Care", system: "C19" }, { code: "HCW2" }],
  },
  { name: "Coding without code", fn: "readChoice", args: [{ code: null, display: null, system: "MOIS-YESNO" }], expected: [] },
  {
    name: "subform/scale selection",
    fn: "readChoice",
    args: [{ selectedKey: "2", value: 2, response: "Moderate", detailResponse: "Moderate pain" }],
    expected: [{ code: "2", display: "Moderate" }],
  },
  { name: "subform unanswered", fn: "readChoice", args: [{ selectedKey: null, value: null, response: null }], expected: [] },
  {
    name: "subform multiple selection",
    fn: "readChoice",
    args: [{ selectedIds: ["a", "b"], selectedLabels: ["Alpha", "Beta"], selectedCount: 2 }],
    expected: [{ code: "a", display: "Alpha" }, { code: "b", display: "Beta" }],
  },
  {
    name: "subform multiple selection with a label only",
    fn: "readChoice",
    args: [{ selectedIds: ["a"], selectedLabels: ["Alpha", "Other text"] }],
    expected: [{ code: "a", display: "Alpha" }, { code: "Other text", display: "Other text" }],
  },
  { name: "subform selection labels without ids", fn: "readChoice", args: [{ selectedLabels: ["Alpha"] }], expected: [{ code: "Alpha", display: "Alpha" }] },
  {
    name: "FindCodeSelect multiple selection",
    fn: "readChoice",
    args: [{ selectedItems: [{ code: "HCW1", display: "Direct Care", system: "C19" }, { code: "HCW2" }] }],
    expected: [{ code: "HCW1", display: "Direct Care", system: "C19" }, { code: "HCW2" }],
  },
  { name: "FindCodeSelect empty multiple selection", fn: "readChoice", args: [{ selectedItems: [] }], expected: [] },
  {
    name: "FindCodeSelect single selection",
    fn: "readChoice",
    args: [{ selectedItem: { code: "Y", display: "Yes", system: "MOIS-YESNO" } }],
    expected: [{ code: "Y", display: "Yes", system: "MOIS-YESNO" }],
  },
  { name: "FindCodeSelect cleared single selection", fn: "readChoice", args: [{ selectedItem: null }], expected: [] },
  {
    name: "FindCodeSelect selection resolved by options",
    fn: "readChoice",
    args: [{ selectedItems: [{ display: "Canada" }] }, COUNTRIES],
    expected: [{ code: "CA", display: "Canada" }],
  },
  { name: "{ value } wrapper around a Coding", fn: "readChoice", args: [{ value: { code: "Y", display: "Yes" } }], expected: [{ code: "Y", display: "Yes" }] },
  { name: "{ value } wrapper around a list", fn: "readChoice", args: [{ value: ["a"] }], expected: [{ code: "a" }] },
  { name: "option-shaped answer", fn: "readChoice", args: [{ label: "Australia", value: "AU" }], expected: [{ code: "AU", display: "Australia" }] },
  { name: "{ key, text } answer", fn: "readChoice", args: [{ key: "routine", text: "Routine" }], expected: [{ code: "routine", display: "Routine" }] },
  { name: "display-only answer", fn: "readChoice", args: [{ display: "Yes" }], expected: [{ code: "Yes", display: "Yes" }] },
  {
    name: "FHIR CodeableConcept",
    fn: "readChoice",
    args: [{ coding: [{ system: "http://loinc.org", code: "LA33-6", display: "Yes" }, { code: "Y" }], text: "Yes" }],
    expected: [{ code: "LA33-6", display: "Yes", system: "http://loinc.org" }],
  },
  { name: "FHIR answer valueCoding", fn: "readChoice", args: [{ valueCoding: { code: "male", display: "Male" } }], expected: [{ code: "male", display: "Male" }] },
  { name: "label string resolved by options", fn: "readChoice", args: ["Australia", COUNTRIES], expected: [{ code: "AU", display: "Australia" }] },
  { name: "code gains its option label", fn: "readChoice", args: ["CA", COUNTRIES], expected: [{ code: "CA", display: "Canada" }] },
  { name: "code matched case-insensitively", fn: "readChoice", args: ["au", COUNTRIES], expected: [{ code: "AU", display: "Australia" }] },
  { name: "label matched case-insensitively", fn: "readChoice", args: [[" canada "], COUNTRIES], expected: [{ code: "CA", display: "Canada" }] },
  { name: "unknown value kept", fn: "readChoice", args: ["ZZ", COUNTRIES], expected: [{ code: "ZZ" }] },
  { name: "stored system kept over option", fn: "readChoice", args: [{ code: "AU", system: "ISO-3166" }, COUNTRIES], expected: [{ code: "AU", display: "Australia", system: "ISO-3166" }] },
  { name: "option system used when the answer has none", fn: "readChoice", args: ["Y", [{ code: "Y", display: "Yes", system: "MOIS-YESNO" }]], expected: [{ code: "Y", display: "Yes", system: "MOIS-YESNO" }] },
  { name: "dform label answer", fn: "readChoice", args: ["Mild", [{ label: "None", state: "0", score: 0 }, { label: "Mild", state: "1", score: 1 }]], expected: [{ code: "1", display: "Mild" }] },
  { name: "scale option by key", fn: "readChoice", args: ["9", [{ value: 0, label: "Unknown", key: "9" }]], expected: [{ code: "9", display: "Unknown" }] },
];

export const READ_DATE_CASES: ValueCase[] = [
  { name: "ISO date is local midnight", fn: "readDate", args: ["2026-01-15"], expected: new Date(2026, 0, 15) },
  { name: "single-digit ISO parts", fn: "readDate", args: ["2026-1-5"], expected: new Date(2026, 0, 5) },
  { name: "DateSelect yyyy.MM.dd", fn: "readDate", args: ["2026.01.15"], expected: new Date(2026, 0, 15) },
  { name: "dd/MM/yyyy", fn: "readDate", args: ["15/01/2026"], expected: new Date(2026, 0, 15) },
  { name: "MM-dd-yyyy", fn: "readDate", args: ["01-15-2026"], expected: new Date(2026, 0, 15) },
  { name: "padded text", fn: "readDate", args: [" 2026-01-15 "], expected: new Date(2026, 0, 15) },
  { name: "impossible day", fn: "readDate", args: ["2026-02-30"], expected: null },
  { name: "impossible dd/MM", fn: "readDate", args: ["31/04/2026"], expected: null },
  { name: "local date-time", fn: "readDate", args: ["2026-01-15T10:30"], expected: new Date(2026, 0, 15, 10, 30) },
  { name: "UTC date-time", fn: "readDate", args: ["2026-01-15T10:30:00Z"], expected: new Date(Date.UTC(2026, 0, 15, 10, 30)) },
  { name: "ISO date-time with milliseconds (DateTimeSelect)", fn: "readDate", args: ["2026-01-15T17:30:00.000Z"], expected: new Date(Date.UTC(2026, 0, 15, 17, 30)) },
  { name: "date-time with an offset", fn: "readDate", args: ["2026-01-15T10:30+02:00"], expected: new Date(Date.UTC(2026, 0, 15, 8, 30)) },
  { name: "DateSelect format with a time", fn: "readDate", args: ["2026.01.15 10:30"], expected: new Date(2026, 0, 15, 10, 30) },
  { name: "yyyy/MM/dd", fn: "readDate", args: ["2026/01/15"], expected: new Date(2026, 0, 15) },
  { name: "impossible time", fn: "readDate", args: ["2026-01-15T25:00"], expected: null },
  { name: "a bare number as text is not a date", fn: "readDate", args: ["5"], expected: null },
  { name: "month-name text is not read", fn: "readDate", args: ["March 15, 2026"], expected: null },
  { name: "epoch milliseconds", fn: "readDate", args: [Date.UTC(2026, 0, 15)], expected: new Date(Date.UTC(2026, 0, 15)) },
  { name: "Date object", fn: "readDate", args: [new Date(2026, 5, 1)], expected: new Date(2026, 5, 1) },
  { name: "invalid Date object", fn: "readDate", args: [new Date(Number.NaN)], expected: null },
  { name: "NaN", fn: "readDate", args: [Number.NaN], expected: null },
  { name: "empty text", fn: "readDate", args: [""], expected: null },
  { name: "blank text", fn: "readDate", args: ["   "], expected: null },
  { name: "null", fn: "readDate", args: [null], expected: null },
  { name: "not a date", fn: "readDate", args: ["not a date"], expected: null },
  { name: "{ value } wrapper", fn: "readDate", args: [{ value: "2026-01-15" }], expected: new Date(2026, 0, 15) },
  { name: "{ date } wrapper", fn: "readDate", args: [{ date: "2026.01.15" }], expected: new Date(2026, 0, 15) },
  { name: "{ display } wrapper", fn: "readDate", args: [{ display: "15/01/2026" }], expected: new Date(2026, 0, 15) },
  { name: "object without a date", fn: "readDate", args: [{ code: "x" }], expected: null },
];

export const VALUE_CASES: ValueCase[] = [
  ...NORMALIZE_OPTION_CASES,
  ...READ_BOOLEAN_CASES,
  ...READ_CHOICE_CASES,
  ...READ_DATE_CASES,
];
