// DefaultsKit — default answers in the exported form: reads a field's,
// column's, cell's or subform entry's default in every saved shape and
// resolves it to the value to seed. Non-rendering helper module in the
// FormulaKit pattern: one namespace object, so consumers keep a single bare
// identifier in engine scope and reference it only inside function bodies
// (component files load in no guaranteed order).
//
//   DefaultsKit.readDefaultAnswer(fieldLike, { shape, bringForward })
//                     -> { kind: "literal" | "today" | "now" | "chart" | "lastObservation", ... } | null
//   DefaultsKit.resolveDefaultAnswer(answer, { now, fieldType, readChart, readLastObservation })
//                     -> the value to seed, or undefined
//   DefaultsKit.temporalKindOf(fieldLike) / isBlankAnswer(value)
//
// A default is seeded only into an empty answer on a new form or a new row.
//
// Generated by scripts/generate-defaults-kit.mjs from packages/form-model/src/defaults.ts.
// Do not edit: change defaults.ts and run `pnpm generate:nhforms`. The shared
// case table (defaults.cases.ts) holds both implementations to the same results.

const DefaultsKit = (() => {
  var DEFAULT_ANSWER_KINDS = ["literal", "today", "now", "chart", "lastObservation"];
  var isRecord = (value) => Boolean(value) && typeof value === "object" && !Array.isArray(value);
  var hasOwn = (value, key) => Object.prototype.hasOwnProperty.call(value, key);
  function cloneValue(value) {
    if (Array.isArray(value)) return value.map((entry) => cloneValue(entry));
    if (isRecord(value)) {
      const out = {};
      for (const key of Object.keys(value)) out[key] = cloneValue(value[key]);
      return out;
    }
    return value;
  }
  function stableJson(value) {
    if (Array.isArray(value)) return `[${value.map(stableJson).join(",")}]`;
    if (isRecord(value)) {
      return `{${Object.keys(value).filter((key) => value[key] !== void 0).sort().map((key) => `${JSON.stringify(key)}:${stableJson(value[key])}`).join(",")}}`;
    }
    return value === void 0 ? "null" : JSON.stringify(value);
  }
  function isBlankAnswer(value) {
    if (value === void 0 || value === null) return true;
    if (typeof value === "string") return value.trim() === "";
    if (Array.isArray(value)) return value.length === 0;
    if (isRecord(value)) return Object.keys(value).length === 0;
    return false;
  }
  var isBlankStoredDefault = (value) => value === void 0 || value === null || value === "" || Array.isArray(value) && value.length === 0;
  var nonEmptyString = (value) => typeof value === "string" && value.trim() ? value.trim() : void 0;
  function isDefaultAnswer(value) {
    if (!isRecord(value)) return false;
    switch (value.kind) {
      case "literal":
        return hasOwn(value, "value") && value.value !== void 0;
      case "today":
      case "now":
        return true;
      case "chart":
        return Boolean(nonEmptyString(value.concept)) || Array.isArray(value.paths) && value.paths.some((path) => Boolean(nonEmptyString(path)));
      case "lastObservation":
        return Boolean(nonEmptyString(value.code)) && (value.system === void 0 || typeof value.system === "string") && (value.lookbackDays === void 0 || typeof value.lookbackDays === "number" && Number.isFinite(value.lookbackDays));
      default:
        return false;
    }
  }
  function normalizeDefaultAnswer(value) {
    if (!isDefaultAnswer(value)) return null;
    switch (value.kind) {
      case "literal":
        return isBlankStoredDefault(value.value) ? null : { kind: "literal", value: cloneValue(value.value) };
      case "today":
        return { kind: "today" };
      case "now":
        return { kind: "now" };
      case "chart": {
        const concept = nonEmptyString(value.concept);
        const paths = (value.paths ?? []).map((path) => nonEmptyString(path)).filter((path) => Boolean(path));
        return { kind: "chart", ...concept ? { concept } : {}, ...paths.length ? { paths } : {} };
      }
      case "lastObservation": {
        const system = nonEmptyString(value.system);
        const lookbackDays = typeof value.lookbackDays === "number" && value.lookbackDays > 0 ? value.lookbackDays : void 0;
        return {
          kind: "lastObservation",
          code: nonEmptyString(value.code),
          ...system ? { system } : {},
          ...lookbackDays !== void 0 ? { lookbackDays } : {}
        };
      }
    }
  }
  function sameDefaultAnswer(left, right) {
    return stableJson(normalizeDefaultAnswer(left) ?? null) === stableJson(normalizeDefaultAnswer(right) ?? null);
  }
  var TABLE_COLUMN_ONLY_TYPES = ["checkbox", "stampButton"];
  var LAYOUT_DISPLAY_CELL_KINDS = ["text", "resources", "computed", "stampButton", "fieldList"];
  function inferDefaultAnswerShape(fieldLike) {
    if (!isRecord(fieldLike)) return "field";
    if (hasOwn(fieldLike, "defaultFromObservation") || hasOwn(fieldLike, "default_from_observation") || hasOwn(fieldLike, "builderField")) {
      return "subformEntry";
    }
    if (typeof fieldLike.type === "string") {
      if (!hasOwn(fieldLike, "prefill") && (hasOwn(fieldLike, "defaultValue") || hasOwn(fieldLike, "default_value"))) return "subformEntry";
      if (TABLE_COLUMN_ONLY_TYPES.includes(fieldLike.type) || hasOwn(fieldLike, "dataPath") || hasOwn(fieldLike, "showInTable") || hasOwn(fieldLike, "withTime")) return "tableColumn";
      return "field";
    }
    if (typeof fieldLike.rawType === "string") return "field";
    if (hasOwn(fieldLike, "inputType") || hasOwn(fieldLike, "fieldId") || typeof fieldLike.kind === "string") return "layoutCell";
    return "field";
  }
  function isLayoutDisplayCell(cell) {
    return typeof cell.kind === "string" && LAYOUT_DISPLAY_CELL_KINDS.includes(cell.kind);
  }
  var DISPLAY_FIELD_TYPES = ["richText", "heading", "section", "hyperlink"];
  function isDisplayField(field) {
    const type = typeof field.type === "string" ? field.type : typeof field.rawType === "string" ? field.rawType : "";
    if (type === "richText") return !(isRecord(field.richTextConfig) && field.richTextConfig.readOnly === false);
    return DISPLAY_FIELD_TYPES.includes(type);
  }
  function temporalKindOf(fieldLike) {
    if (!isRecord(fieldLike)) return null;
    const type = typeof fieldLike.type === "string" ? fieldLike.type : "";
    const inputType = typeof fieldLike.inputType === "string" ? fieldLike.inputType : "";
    const rawType = typeof fieldLike.rawType === "string" ? fieldLike.rawType : "";
    if (type === "datetime" || rawType === "datetime") return "dateTime";
    if (type === "time" || inputType === "time" || rawType === "time") return "time";
    if (type === "date" || inputType === "date" || rawType === "date") {
      const dateConfig = isRecord(fieldLike.dateConfig) ? fieldLike.dateConfig : null;
      return fieldLike.withTime === true || dateConfig?.withTime === true || fieldLike.dateWithTime === true ? "dateTime" : "date";
    }
    return null;
  }
  function normalizeTemporalKind(fieldType) {
    if (fieldType === "date") return "date";
    if (fieldType === "dateTime" || fieldType === "datetime") return "dateTime";
    if (fieldType === "time") return "time";
    return null;
  }
  var TOKEN_KINDS = ["today", "now", "nextDateAfterLastRow"];
  var TODAY_SOURCE_PATHS = ["system.currentDate", "system.currentDateTime"];
  function sourcePathsOf(cell) {
    const paths = [cell.sourcePath, ...Array.isArray(cell.sourcePaths) ? cell.sourcePaths : []].map((path) => nonEmptyString(path)).filter((path) => Boolean(path));
    return paths.filter((path, index) => paths.indexOf(path) === index);
  }
  function todayBindingOf(cell) {
    const paths = sourcePathsOf(cell);
    if (paths.length === 0 || cell.sourceMode !== "initial") return null;
    if (!paths.every((path) => TODAY_SOURCE_PATHS.includes(path))) return null;
    return paths[0] === "system.currentDateTime" ? { kind: "now" } : { kind: "today" };
  }
  function hasTodayFlag(fieldLike) {
    const dateConfig = isRecord(fieldLike.dateConfig) ? fieldLike.dateConfig : null;
    return dateConfig?.prefillToday === true || fieldLike.prefillToday === true;
  }
  function yesNoOptionTokens(entry) {
    const options = Array.isArray(entry.options) && entry.options.length > 0 ? entry.options : ["Yes", "No"];
    return [options[0], options[1]];
  }
  function optionTokens(option) {
    if (option === void 0 || option === null) return [];
    if (!isRecord(option)) return [String(option)];
    return [option.value, option.key, option.id, option.code, option.label, option.text, option.display].filter((token) => token !== void 0 && token !== null).map((token) => String(token));
  }
  function optionStoredToken(option) {
    if (!isRecord(option)) return option === void 0 || option === null ? null : option;
    const token = option.value ?? option.key ?? option.id ?? option.label ?? option.text;
    return token === void 0 || token === null ? null : token;
  }
  var sameToken = (left, right) => String(left).trim().toLowerCase() === right.trim().toLowerCase();
  function descriptorFromStoredValue(value, { underscoreTokens, entry }) {
    if (isBlankStoredDefault(value)) return null;
    if (underscoreTokens && value === "__today") return { kind: "today" };
    if (underscoreTokens && value === "__now") return { kind: "now" };
    if (isRecord(value) && typeof value.kind === "string" && TOKEN_KINDS.includes(value.kind)) {
      if (value.kind === "today") return { kind: "today" };
      if (value.kind === "now") return { kind: "now" };
      return null;
    }
    if (entry && entry.type === "booleanYesNo" && (typeof value === "string" || typeof value === "number")) {
      const [on, off] = yesNoOptionTokens(entry);
      if (optionTokens(on).some((token) => sameToken(value, token))) return { kind: "literal", value: true };
      if (optionTokens(off).some((token) => sameToken(value, token))) return { kind: "literal", value: false };
    }
    return { kind: "literal", value: cloneValue(value) };
  }
  function observationBindingOf(entry) {
    const binding = entry.defaultFromObservation ?? entry.default_from_observation;
    if (!isRecord(binding)) return null;
    const code = nonEmptyString(binding.observationCode ?? binding.observation_code ?? binding.code);
    if (!code) return null;
    const system = nonEmptyString(binding.system);
    const lookbackDays = typeof binding.lookbackDays === "number" && Number.isFinite(binding.lookbackDays) && binding.lookbackDays > 0 ? binding.lookbackDays : void 0;
    return {
      kind: "lastObservation",
      code,
      ...system ? { system } : {},
      ...lookbackDays !== void 0 ? { lookbackDays } : {}
    };
  }
  function readLegacyDefault(fieldLike, shape, bringForward) {
    if (shape === "subformEntry") {
      if (bringForward !== false) {
        const observation = observationBindingOf(fieldLike);
        if (observation) return observation;
      }
      const stored = hasOwn(fieldLike, "defaultValue") ? fieldLike.defaultValue : fieldLike.default_value;
      return descriptorFromStoredValue(stored, { underscoreTokens: true, entry: fieldLike });
    }
    if (!isBlankStoredDefault(fieldLike.prefill)) {
      return descriptorFromStoredValue(fieldLike.prefill, { underscoreTokens: false });
    }
    if (hasTodayFlag(fieldLike)) {
      const temporal = temporalKindOf(fieldLike);
      if (temporal === "date") return { kind: "today" };
      if (temporal === "dateTime") return { kind: "now" };
    }
    if (shape === "layoutCell") {
      if (sourcePathsOf(fieldLike).length > 0) return todayBindingOf(fieldLike);
      return descriptorFromStoredValue(fieldLike.defaultValue, { underscoreTokens: false });
    }
    return null;
  }
  function hasLegacyDefaultKey(fieldLike, shape) {
    const present = (record, key) => record[key] !== void 0;
    if (shape === "subformEntry") {
      return ["defaultValue", "default_value", "defaultFromObservation", "default_from_observation"].some((key) => present(fieldLike, key));
    }
    if (present(fieldLike, "prefill") || present(fieldLike, "prefillToday")) return true;
    if (isRecord(fieldLike.dateConfig) && present(fieldLike.dateConfig, "prefillToday")) return true;
    if (shape === "layoutCell") {
      if (todayBindingOf(fieldLike)) return true;
      if (sourcePathsOf(fieldLike).length === 0 && present(fieldLike, "defaultValue")) return true;
    }
    return false;
  }
  function withoutLegacyDefault(fieldLike, shape) {
    const next = { ...fieldLike };
    if (shape === "subformEntry") {
      delete next.defaultValue;
      delete next.default_value;
      delete next.defaultFromObservation;
      delete next.default_from_observation;
      return next;
    }
    delete next.prefill;
    delete next.prefillToday;
    if (isRecord(next.dateConfig) && hasOwn(next.dateConfig, "prefillToday")) {
      const { prefillToday: _prefillToday, ...dateConfig } = next.dateConfig;
      next.dateConfig = dateConfig;
    }
    if (shape === "layoutCell" && !isLayoutDisplayCell(next)) {
      if (todayBindingOf(next)) {
        delete next.sourcePath;
        delete next.sourcePaths;
        delete next.sourceMode;
        delete next.sourceFormat;
        delete next.sourceFallback;
        delete next.defaultValue;
      } else if (sourcePathsOf(next).length === 0) {
        delete next.defaultValue;
      }
    }
    return next;
  }
  function applyLegacyMirror(next, answer, shape, original) {
    if (!answer) return;
    if (shape === "subformEntry") {
      if (answer.kind === "literal") {
        if (next.type === "booleanYesNo" && typeof answer.value === "boolean") {
          const [on, off] = yesNoOptionTokens(next);
          next.defaultValue = optionStoredToken(answer.value ? on : off);
        } else {
          next.defaultValue = cloneValue(answer.value);
        }
      } else if (answer.kind === "today") {
        next.defaultValue = "__today";
      } else if (answer.kind === "now") {
        next.defaultValue = "__now";
      } else if (answer.kind === "lastObservation") {
        const previous = original.defaultFromObservation ?? original.default_from_observation;
        const aspect = isRecord(previous) && nonEmptyString(previous.observationCode ?? previous.observation_code) === answer.code && typeof previous.aspect === "string" ? previous.aspect : void 0;
        next.defaultFromObservation = {
          observationCode: answer.code,
          ...answer.system ? { system: answer.system } : {},
          ...answer.lookbackDays !== void 0 ? { lookbackDays: answer.lookbackDays } : {},
          ...aspect ? { aspect } : {}
        };
      }
      return;
    }
    if (answer.kind === "literal") {
      next.prefill = cloneValue(answer.value);
    } else if (answer.kind === "today" || answer.kind === "now") {
      const temporal = temporalKindOf(original);
      if (temporal === "date" || temporal === "dateTime") {
        next.dateConfig = { ...isRecord(next.dateConfig) ? next.dateConfig : {}, prefillToday: true };
      }
    }
  }
  function readDefaultAnswer(fieldLike, options = {}) {
    if (!isRecord(fieldLike)) return null;
    const shape = options.shape ?? inferDefaultAnswerShape(fieldLike);
    if (shape === "layoutCell" && isLayoutDisplayCell(fieldLike)) return null;
    if (shape === "field" && isDisplayField(fieldLike)) return null;
    const legacy = readLegacyDefault(fieldLike, shape, options.bringForward);
    const stored = normalizeDefaultAnswer(fieldLike.defaultAnswer);
    let answer = legacy;
    if (stored && !hasLegacyDefaultKey(fieldLike, shape)) {
      answer = stored;
    } else if (stored) {
      const mirrored = withoutLegacyDefault(fieldLike, shape);
      applyLegacyMirror(mirrored, stored, shape, fieldLike);
      const expected = readLegacyDefault(mirrored, shape, options.bringForward);
      if (sameDefaultAnswer(expected, legacy)) answer = stored;
    }
    if (answer && answer.kind === "lastObservation" && options.bringForward === false) {
      answer = readLegacyDefault(fieldLike, shape, false);
    }
    return answer ? cloneValue(answer) : null;
  }
  function writeDefaultAnswer(fieldLike, answer, options = {}) {
    const original = fieldLike;
    const shape = options.shape ?? inferDefaultAnswerShape(original);
    const normalized = normalizeDefaultAnswer(answer);
    const next = withoutLegacyDefault(original, shape);
    applyLegacyMirror(next, normalized, shape, original);
    if (normalized) next.defaultAnswer = normalized;
    else delete next.defaultAnswer;
    return next;
  }
  function defaultAnswerPatch(fieldLike, answer, options = {}) {
    const before = fieldLike;
    const after = writeDefaultAnswer(fieldLike, answer, options);
    const patch = {};
    const keys = Object.keys(before).concat(Object.keys(after).filter((key) => !hasOwn(before, key)));
    for (const key of keys) {
      if (stableJson(before[key]) === stableJson(after[key]) && hasOwn(before, key) === hasOwn(after, key)) continue;
      if (hasOwn(after, key)) patch[key] = after[key];
      else patch[key] = key === "prefill" || key === "defaultAnswer" ? null : void 0;
    }
    return patch;
  }
  var pad2 = (value) => String(value).padStart(2, "0");
  function formatLocalDate(date) {
    return `${date.getFullYear()}-${pad2(date.getMonth() + 1)}-${pad2(date.getDate())}`;
  }
  function formatLocalDateTime(date) {
    return `${formatLocalDate(date)}T${pad2(date.getHours())}:${pad2(date.getMinutes())}`;
  }
  function resolveDefaultAnswer(answer, context) {
    const normalized = normalizeDefaultAnswer(answer);
    if (!normalized) return void 0;
    const now = context && context.now instanceof Date && !Number.isNaN(context.now.getTime()) ? context.now : /* @__PURE__ */ new Date();
    const temporal = normalizeTemporalKind(context?.fieldType ?? null);
    switch (normalized.kind) {
      case "literal":
        return cloneValue(normalized.value);
      case "today":
        return temporal === "time" ? void 0 : formatLocalDate(now);
      case "now":
        if (temporal === "date") return formatLocalDate(now);
        if (temporal === "time") return `${pad2(now.getHours())}:${pad2(now.getMinutes())}`;
        return formatLocalDateTime(now);
      case "chart": {
        if (typeof context?.readChart !== "function") return void 0;
        const value = context.readChart({
          ...normalized.concept ? { concept: normalized.concept } : {},
          ...normalized.paths ? { paths: [...normalized.paths] } : {}
        });
        return isBlankAnswer(value) ? void 0 : value;
      }
      case "lastObservation": {
        if (typeof context?.readLastObservation !== "function") return void 0;
        const value = context.readLastObservation(normalized.code, normalized.system, normalized.lookbackDays);
        return isBlankAnswer(value) ? void 0 : value;
      }
    }
    return void 0;
  }

  return {
    DEFAULT_ANSWER_KINDS,
    defaultAnswerPatch,
    formatLocalDate,
    formatLocalDateTime,
    inferDefaultAnswerShape,
    isBlankAnswer,
    isDefaultAnswer,
    readDefaultAnswer,
    resolveDefaultAnswer,
    sameDefaultAnswer,
    temporalKindOf,
    writeDefaultAnswer,
  }
})()
