/**
 * Fluent/Fabric Namespace
 *
 * Provides Fluent UI components under Fluent.*, Fabric.*, and FluentUI.* namespaces
 * for compatibility with MOIS forms that use these naming conventions.
 */

import {
  Stack,
  StackItem,
  Text,
  TextField,
  Dropdown,
  DatePicker,
  PrimaryButton,
  DefaultButton,
  Label,
  Icon,
  FontIcon,
  IconButton,
  ActionButton as FluentActionButton,
  Toggle,
  Checkbox,
  ChoiceGroup,
  ComboBox,
  SpinButton,
  Separator,
  Persona,
  PersonaSize,
  MessageBar,
  MessageBarType,
  Link,
  Spinner,
  SpinnerSize,
  Panel,
  PanelType,
  Dialog,
  DialogType,
  DialogFooter,
  Modal,
  Layer,
  Overlay,
  Callout,
  TooltipHost,
  TeachingBubble,
  Pivot,
  PivotItem,
  Nav,
  Breadcrumb,
  CommandBar,
  DetailsList,
  DetailsListLayoutMode,
  SelectionMode,
  List,
  GroupedList,
  SearchBox,
  MaskedTextField,
  TagPicker,
  ColorPicker,
  SwatchColorPicker,
  Rating,
  Slider,
  ProgressIndicator,
  Shimmer,
  FocusZone,
  FocusZoneDirection,
  ScrollablePane,
  Sticky,
  StickyPositionType,
  ResizeGroup,
  OverflowSet,
  DocumentCard,
  DocumentCardTitle,
  DocumentCardPreview,
  HoverCard,
  Facepile,
  Image,
  ThemeProvider,
  mergeStyles,
  mergeStyleSets,
} from '@fluentui/react';

/**
 * FluentNamespace - Contains all Fluent UI components
 * Used as Fabric.*, Fluent.*, and FluentUI.* in forms
 */
export const FluentNamespace = {
  // Core components
  Stack,
  StackItem,
  Text,
  TextField,
  Dropdown,
  DatePicker,
  PrimaryButton,
  DefaultButton,
  Label,
  Icon,
  FontIcon,
  IconButton,
  ActionButton: FluentActionButton,
  CommandButton: FluentActionButton,
  Toggle,
  Checkbox,
  ChoiceGroup,
  ComboBox,
  SpinButton,
  Separator,
  Persona,
  PersonaSize,
  MessageBar,
  MessageBarType,
  Link,
  Spinner,
  SpinnerSize,
  // Panels and dialogs
  Panel,
  PanelType,
  Dialog,
  DialogType,
  DialogFooter,
  Modal,
  Layer,
  Overlay,
  Callout,
  TooltipHost,
  TeachingBubble,
  // Navigation
  Pivot,
  PivotItem,
  Nav,
  Breadcrumb,
  CommandBar,
  // Lists and data
  DetailsList,
  DetailsListLayoutMode,
  SelectionMode,
  List,
  GroupedList,
  // Search and input
  SearchBox,
  MaskedTextField,
  TagPicker,
  ColorPicker,
  SwatchColorPicker,
  Rating,
  Slider,
  // Progress and loading
  ProgressIndicator,
  Shimmer,
  // Layout helpers
  FocusZone,
  FocusZoneDirection,
  ScrollablePane,
  Sticky,
  StickyPositionType,
  ResizeGroup,
  OverflowSet,
  // Cards and content
  DocumentCard,
  DocumentCardTitle,
  DocumentCardPreview,
  HoverCard,
  Facepile,
  Image,
  // Theming
  ThemeProvider,
  mergeStyles,
  mergeStyleSets,
  // Enums for dropdowns and menus
  SelectableOptionMenuItemType: { Normal: 0, Divider: 1, Header: 2 },
  // Aliases
  Divider: Separator,
};

// Re-export FluentActionButton for use in scope builders
export { FluentActionButton };
